trufnetwork/kwil-db

.github/workflows/ci.yaml, cmd/kwil-cli/cmds/database/batch.go, cmd/kwil-cli/cmds/database/call.go, cmd/kwil-cli/cmds/database/execute.go, common/common.go, core/client/client.go, core/client/client_test.go, core/go.mod, core/types/transactions/payloads.go, core/types/transactions/payloads_test.go, core/types/transactions/transaction_test.go, internal/engine/execution/global.go, internal/engine/execution/procedure.go, internal/services/grpc/txsvc/v1/call.go, internal/txapp/routes.go
Rebirth of https://github.com/kwilteam/kwil-db/pull/520
=> respect and pass null / omitted arguments

.github/workflows/ci.yaml, .github/workflows/on-main.yml, core/rpc/client/gateway/http/client.go
This pr backport #564 to v0.6.6, along with the fix on CI(due to opensource)
=> [backport: v0.6.6] fix gateway client auth error

README.md, Taskfile.yml, build/package/docker/postgres.dockerfile
The commands all run but I didn't carefully proofread this since I want it reviewable asap and it may conflict with https://github.com/kwilteam/kwil-db/pull/549
[Rendered.](https://github.com/kwilteam/kwil-db/blob/d4a61ad588524d303d2ddee2b0fbc8b626b94926/README.md)
Complements https://github.com/kwilteam/docs/pull/82
=> more readme updates and pg tasks

.goreleaser.yaml
=> [backport v0.6.6] update go releaser conf

README.md, deployments/compose/kwil/docker-compose.yml, test/integration/docker-compose-dev.yml, test/integration/docker-compose.yml.template
This allow `docker compose` to build kwild in one go
=> chore: compose with build

cmd/kwild/server/server.go, extensions/oracles/eth_deposits/deposits.go, extensions/oracles/oracles.go, internal/oracles/mgr.go
Fixes 
https://github.com/kwilteam/kwil-db/issues/577
=> fix: unused err check and deposit bug

test/integration/kwild_test.go, test/specifications/validator_ops.go
Updated integration tests to test out the below negative path scenarios for validators update transactions
=> Add negative path testcases for validator transactions

internal/sql/pg/repl.go, internal/sql/pg/repl_test.go, internal/sql/pg/replmon.go
https://github.com/kwilteam/kwil-db/pull/597 but for release
Last thing, I think, before tag.
Untracked transaction are intended to have a sequence number of -1, indicating there was no sequence update, which is used by transactions from a pg.DB instance to correlate WAL data updates with a certain transaction.
This commit fixes the replication monitor to work correctly with concurrent untracked transactions by:
- reset the seq var to -1 in the captureRepl loop after each commit
- when a commit is reached with seq still -1 (not updated by an untracked transaction), do NOT send the commit ID on the channel
This also beefs up the logging and error handling in unexpected cases, which corresponds to improper use of replMon methods or concurrent (ab)use of the sentry table to break correct …
=> [release-v0.7] pg: reset seq num in replication after commit msg

.github/workflows/kgw-test-reuse.yaml, .github/workflows/main.yaml, .github/workflows/manual-test-kgw.yaml, .github/workflows/release.yaml, .github/workflows/trigger-test-kgw.yaml
This pr fix couple CI issue:
- version parsing erro in release.yaml
- try checkout to pr branch using sha instead of branch, bcz it's not available in kwilteam repo if pr comes from forked repo
I used https://github.com/nektos/act to test locally, which I really recommend, it could save a lot of time
=> CI/fix release & trigger workflow

cmd/kwild/config/folders.go, core/types/hex.go, go.mod, go.sum, internal/abci/cometbft/node.go, internal/abci/cometbft/privval/privvalidator.go, internal/abci/cometbft/privval/privvalidator_test.go, internal/abci/cometbft/reset.go, test/go.mod, test/go.sum
=> privval,config,cometbft: stop using cometbft/libs that are becoming internal

.github/workflows/ci.yaml, .github/workflows/kgw-test-reuse.yaml, .github/workflows/main.yaml, .github/workflows/manual-test-kgw.yaml, .github/workflows/release.yaml, deployments/compose/kwil/docker-compose.override.yml.example
This pr will run kwil-js once any PR merged into main. Also changed kwil-test-reuse, so that a kwil-js can use  branch/tag/sha input
=> ci: run kwil-js test

.github/workflows/kgw-test-reuse.yaml, .github/workflows/release.yaml, deployments/compose/kwil/docker-compose.override.yml.example
=> [v0.7.2] ci: run kwil-js test 

core/gatewayclient/client.go, core/rpc/client/function/http/client.go, core/rpc/client/user/http/client.go, core/rpc/client/user/http/error.go, internal/services/grpc/txsvc/v1/query.go, internal/version/version.go
This backports:
- #507 
- #624 
- #645
- #647
=> [v0.6.7] bundle backport

internal/sql/sqlite/connection.go, internal/sql/sqlite/result.go
Solves https://kwilteam.slack.com/archives/C0578NPEU21/p1712918350300909
=> Fix leftjoin null

core/gatewayclient/client.go, core/types/gateway/gateway.go
=> [v0.6.8] core: gateway client authn precheck

core/gatewayclient/client.go, core/types/gateway/gateway.go, internal/version/version.go
=> [v0.7.3] core: gwclient auth precheck

core/rpc/client/error.go, core/rpc/client/function/http/client.go
=> [v0.6.8] func client wrap error

cmd/kwil-cli/cmds/account/balance.go, cmd/kwild/server/utils.go, internal/services/grpc/txsvc/v1/broadcast.go, test/driver/cli_driver.go
=> [v0.6.8] tx broadcast debugging

core/gatewayclient/client.go, parse/parse.go, test/acceptance/kwild_test.go, test/acceptance/test-data/test_db.kf, test/integration/kgw_test.go, test/integration/test-data/test_db.kf, test/specifications/execute_call_action.go, test/specifications/utils.go
This pr 
- adds `Call` function to `GatewayClient`, so GatewayClient will do proper authn if required
- update KGWTest to test against procedure
=> fix kgw client call action

cmd/kwil-cli/cmds/common/authinfo.go, cmd/kwil-cli/cmds/common/authinfo_test.go, cmd/kwil-cli/cmds/common/roundtripper.go
=> [v0.7.5] kgw cookie multi providers

cmd/kwil-cli/cmds/common/authinfo.go, cmd/kwil-cli/cmds/common/authinfo_test.go, cmd/kwil-cli/cmds/common/roundtripper.go
=> [v0.6.8] kgw cookie multi providers

core/types/transactions/payload_schema.go
Fixed a bug where foreign procedures were not being rlp encoded.
=> fixed rlp encode bug for foreign procedures

internal/services/jsonrpc/server.go
The `net/http.Server` by default recovers panics, but silently.  This adds a very simple middleware stack with a recoverer handler on the outside. This would have identified a silent panic in CheckTx during @charithabandi 's work.
```
2024-05-10T16:26:28.476-05:00	warn	kwild.user-jsonrpc-server	jsonrpc/server.go:162	panic:
goroutine 399 [running]:
runtime/debug.Stack()
/home/jon/go122/src/runtime/debug/stack.go:24 +0x5e
github.com/kwilteam/kwil-db/internal/services/jsonrpc.NewServer.recoverer.func2.1()
/home/jon/kwil/git/kwil-db-again/internal/services/jsonrpc/server.go:161 +0x7d
panic({0x1642020?, 0x1bd7b60?})
/home/jon/go122/src/runtime/panic.go:770 +0x132
github.com/kwilteam/kwil-db/internal/abci.(*AbciApp).CheckTx(0xc0000f2be0, {0x1bf1428, 0x29fce20}, 0xc009372ac0) …
```
=> services/jsonrpc: recover http handler panic with logged stack

core/types/transactions/payload_schema.go
=> core/types/transactions: rlp nil proc returns

build/package/docker/kwild.debug.dockerfile
This makes the kwild debug image work
=> chore: update debug dockerfile

internal/sql/pg/tx.go
This backports https://github.com/kwilteam/kwil-db/pull/744 to `release-v0.7`
=> [v0.7.6] pg: always release conn on commit/rollback error

cmd/common/display/message.go, internal/services/grpc/txsvc/v1/tx_query.go
Minor fixes related to processing nil Transactions in the TxQuery response for unconfirmed transactions.
=> Fix issues with TxQuery for unconfirmed transactions

.github/workflows/kgw-test-reuse.yaml, test/specifications/eth_deposits.go
This will fix the kgw test on main for kwil-js, it's failing https://github.com/kwilteam/kwil-db/actions/runs/9102720328/job/25022987925.
~~This run https://github.com/kwilteam/kwil-db/actions/runs/9102996054 (against kwild `main` branch) should success before we merge this PR. And for this PR I pushed a branch to this repo, will delete afterward.~~ This rerun won't work.
=> ci: fix kgw test workflow

cmd/kwild/server/build.go
Genesis data restoration has a check for an already-initialized database on start up.  This was creating a `pg.DB` instance, which is the heavyweight type that does much more than just provide a DB connection.  We don't want it to create the replication slot, triggers, or any other stuff required by kwild to run.
This change instead uses a `pg.Pool`, which is a barebones DB connection  so we can do the `GetValidators`  query and nothing else.
This also rearranges the conditions in the early return from `restoreDB` so that it is more likely to short-circuit and not bother doing the actual `isDbInitialized` check.  For instance, if state sync were disabled or `DataAppHash` were empty, the `isDbInitialized` check doesn't need to be done.
The effect is faster startup, with less confusing logs …
=> kwild: streamline db is-initialized check

internal/sql/pg/sql.go, test/specifications/types.go
Fixes https://github.com/kwilteam/kwil-db/issues/774
=> fix incorrect max calculation in  uint256 domain

core/rpc/client/function/function.go, core/rpc/client/function/http/client.go, core/rpc/client/function/jsonrpc/client.go, core/rpc/client/gateway/gateway.go, core/rpc/client/gateway/jsonrpc/client.go, core/rpc/client/jsonrpc.go, internal/services/jsonrpc/funcsvc/service.go
This pr adds a jsonrpc client for function service.   
UPDATE:  After this is merge, kwil-db/core tag should be updated
=> Feature: function jsonrpc client

cmd/kwild/server/build.go, internal/txapp/txapp.go
The cometbft node constructor starts it using the ABCI app methods before we've actually started everything else running. Right away it calls `InitChain`, which prepares the initial DB transaction for the initial block.  If we shutdown before block 1's `FinalizeBlock`/`Commit`, we're left with that db tx open. This can happen if e.g. one of the servers fails to start if a TCP port is in use.
**Before**
```
{"level":"error","ts":1717107822.808482,"logger":"kwild.server","caller":"server/server.go:220","msg":"server error","error":"listen tcp 0.0.0.0:8484: bind: address already in use","goversion":"go1.22.3","mod_version":"(devel)","revision":"1661f0faef70326db0fcc555c9a4d5f1a4f05efd","build_time":1717097547,"dirty":true,"stacktrace":"github.com/kwilteam/kwil-db/cmd/kwild/server.(*Server).St …
```
=> txapp: close active txns on early shutdown

cmd/kwil-cli/cmds/utils/parse.go
This PR adds additional info for parse debugging. I originally made these changes to help me debug https://github.com/truflation/tsn/pull/295
It adds the generated plpgsql for debugging.
=> additional parse debug info

internal/engine/execution/global.go, internal/engine/execution/procedure.go, internal/engine/execution/queries.go, internal/engine/execution/queries_test.go, internal/engine/execution/schema_v07.go
This is a little bit hacky, but I believe it is the best we can do. This _should_ work for network migrations, however there could potentially be edge cases. I think I need to spend some more time thinking about how this can be done in the future, but as far as this release goes, it should work.
It ended up being less code to write that I thought, but it does feel extremely messy and hard to maintain long term.
=> V07 snapshots

UPGRADING.md
An initial draft of the `UPGRADING.md` file to assist users with upgrading between versions.
I drew inspiration from CometBFT's [`UPGRADING.md` file](https://github.com/cometbft/cometbft/blob/main/UPGRADING.md).
Content for this section drew from [this discussion](https://github.com/kwilteam/kwil-db/discussions/668) and [wiki](https://github.com/kwilteam/kwil-db/wiki/Kwil-v0.8).
The links should work once [docs#105](https://github.com/kwilteam/docs/pull/105) and [docs#108](https://github.com/kwilteam/docs/pull/108) are merged and published.
This is certainly a first draft. Let me know if any information is missing or if you have alternative recommendations for how to present this information.
=> docs: create UPGRADING.md

internal/engine/execution/global.go, internal/voting/voting.go, parse/antlr.go, parse/parse_test.go
Working branch for working through other parse bugs.
Currently solves:
- https://github.com/kwilteam/kwil-db/issues/809
=> fixed limit expression parse bug

cmd/kwild/config/default_config.toml, cmd/kwild/config/flags.go, cmd/kwild/config/test_data/config.toml, cmd/kwild/root/root.go, cmd/kwild/root/root_test.go, cmd/kwild/server/build.go, internal/abci/abci.go, internal/abci/cometbft/node.go, internal/statesync/codes.go, internal/statesync/snapshotter.go, internal/statesync/statesync.go, internal/statesync/store.go, internal/txapp/txapp.go
Backports:
- https://github.com/kwilteam/kwil-db/pull/815
Will also wait for https://github.com/kwilteam/kwil-db/pull/813 and https://github.com/kwilteam/kwil-db/pull/814
We should make sure to rebase and merge
=> Backport fixes

.github/workflows/release.yaml
=> [0.8.2] backport release workflow update

internal/txapp/txapp.go
Backports https://github.com/kwilteam/kwil-db/pull/822
=> [v0.8.2] change log level for failed resolutions

internal/sql/pg/repl.go
Fix not passing a context to a function where it should be passed
=> pass context to SendStandbyStatusUpdate

build/package/docker/kwild.dockerfile, cmd/kwil-admin/nodecfg/toml.go, cmd/kwild/config/config.go, cmd/kwild/config/config_test.go, cmd/kwild/config/default_config.toml, cmd/kwild/config/reset.go, cmd/kwild/config/test_data/config.toml, cmd/kwild/server/server.go
Fixes the default directors for snapshot and statesync not being in the root directory.
=> fixed default snapshot and statesync dirs

extensions/hooks/hooks.go, internal/txapp/txapp.go
Backports https://github.com/kwilteam/kwil-db/pull/846
=> backport hooks to v0.8

extensions/hooks/hooks.go, internal/txapp/txapp.go
backports https://github.com/kwilteam/kwil-db/pull/846
=> backport hooks to v0.7

cmd/kwil-admin/nodecfg/generate.go, cmd/kwild/config/config.go, cmd/kwild/root/root.go
=> [0.8.2] Fix/kwil admin config (#829)

parse/errors.go, parse/parse.go, parse/parse_test.go
Fixes a panic found when parsing a procedure that expects a return but does not return anything.
We tested for this with schema parsing, but the panic actually occurred when analyzing a procedure relative to a schema, so it slipped through our test cases. I've made a new test case to check for this.
=> fixed panic on parser returns

parse/errors.go, parse/parse.go, parse/parse_test.go
backports https://github.com/kwilteam/kwil-db/pull/851
@KwilLuke once this is merged you will need to update the admin
=> fixed panic on parser returns (#851)

internal/engine/generate/plpgsql.go, internal/engine/integration/procedure_test.go
backports https://github.com/kwilteam/kwil-db/pull/854
=> Backport unary fix

parse/antlr.go, parse/parse_test.go
Resolves https://github.com/kwilteam/kwil-db/issues/860, and handles similar edge cases
=> fix: unknown columns in indexes / foreign keys

parse/antlr.go, parse/parse_test.go
Backports https://github.com/kwilteam/kwil-db/pull/862
=> [v0.8.3] fix: unknown columns in indexes / foreign keys

parse/ast.go
backports https://github.com/kwilteam/kwil-db/pull/864
=> [v0.8.3] removed an unneeded uuid case

cmd/kwild/server/build.go
Resolves https://github.com/kwilteam/kwil-db/issues/835
This 10 second timeout is somewhat arbitrary, but I don't think it demands a config setting.  Virtually any working HTTP server on a healthy network can respond in that time.  If it doesn't it is either dead, firewalled, or the network is misconfigured.  In any case, we cannot hang forever here.
=> kwild: add a timeout to statesync rpc setup

parse/parse.go
This PR adds a `ParseSQLWithoutValidation` function, CC @jchappelow
=> parse sql without validation

.editorconfig
=> set tab_width = 4

cmd/kwil-cli/cmds/utils/test.go, testing/testing.go
While using the testing framework, I ran into a few minor UX things. I actually made this a couple weeks ago, but forgot to push it up. It accounts for
- If a test is stopped mid-execution, the test container might not be torn down. If the test is run and there is already a container, it will give the option to tear it down. This can be automated using the `-Y` flag.
- The CLI only logs pertinent information (previously it logged a lot of unnecessary info), and logs in plaintext rather than JSON
=> minor enhancements to kwil testing tools

cmd/kwil-cli/cmds/utils/dbid.go, cmd/kwil-cli/cmds/utils/utils.go, internal/engine/integration/procedure_test.go, parse/functions.go
While putting together an example, I ran into two things I wish I had: a function to generate DBIDs, and a CLI util to generate DBIDs.
=> feat: dbid util function and cli command

common/common.go, internal/engine/execution/queries.go, internal/services/jsonrpc/usersvc/service.go, internal/txapp/routes.go, parse/contextual.go, test/acceptance/test-data/contextual_vars.kf, test/specifications/contextual_vars.go
Adds `@authenticator`, which prints the string of the authenticator. Will backport to preview once merged
=> feat: @authenticator

testing/testing.go
Resolves https://github.com/kwilteam/kwil-db/issues/930
=> fix: testing index out of range bug

.github/workflows/ci.yaml, cmd/kwil-admin/nodecfg/toml.go, cmd/kwild/config/config.go, cmd/kwild/config/default_config.toml, cmd/kwild/config/flags.go, cmd/kwild/config/test_data/config.toml, cmd/kwild/server/build.go, internal/services/jsonrpc/server.go
=> [0.8] add app.rpc-req-limit / cfg.AppCfg.RPCMaxReqSize

cmd/kwild/config/config.go, cmd/kwild/config/flags.go
Fixes a couple incorrect flags as well as removes unneeded code from migrations
=> Flag underscores

internal/abci/abci.go
node should create a snapshot if:
- none exists
- it is height 1 (genesis+1)
- it is not doing blocksync to some much larger height
- height is a multiple of snapshot duration
=> Create snapshots if snapshots are enabled and none exists

core/types/schema.go, internal/engine/generate/table.go, internal/engine/generate/utils.go, internal/engine/integration/deployment_test.go, internal/engine/integration/procedure_test.go, parse/analyze.go, parse/antlr.go, parse/errors.go, parse/parse_test.go
Resolves all errors in https://github.com/kwilteam/kwil-db/issues/896
=> fix: many parse errors

core/types/transactions/payloads.go, core/types/transactions/payloads_test.go
```
core/types/transactions: remove PayloadTypeCallAction
The transactions.PayloadType enum list possible transaction
payloads, however an ActionCall is not a payload in a transaction,
only CallMessage.
The Transaction and CallMessage types are similar in construction,
but we should not recognize an ActionCall as valid if it is encountered
in a Transaction.Body.  No blockchain transaction, which is processed
by consensus should contain this as there is no applicable TxApp
route to handle such a transaction.
```
Replaces https://github.com/kwilteam/kwil-db/pull/949 and resolves #904
=> core/types/transactions: remove PayloadTypeCallAction

core/client/README.md
Very minor thing, but I noticed a few slightly incorrect or outdated things in the client docs and they were really bugging me.
Resolves https://github.com/kwilteam/kwil-db/issues/978
=> update client docs

cmd/common/generate/generate.go, cmd/kwil-cli/cmds/utils/dbid.go, cmd/kwil-cli/cmds/utils/generate_key.go, cmd/kwil-cli/cmds/utils/utils.go
Adds a utility to kwil-cli that allows users to generate ECDSA keys
=> added kwil-cli utils generate-key

.github/workflows/release.yaml
This pr changes release workflow to support kwil-db v0.9
=> ci: release workflow support v0.9

cmd/kwil-admin/cmds/setup/cmd.go, cmd/kwil-admin/cmds/setup/genesis-hash.go, cmd/kwil-admin/cmds/setup/genesis.go, common/chain/chaincfg.go
Adds a `kwil-admin setup genesis` command. This creates a genesis file, allowing users to automatically generate valid genesis.json files that are up to date
=> kwil-admin: setup genesis command

cmd/kwild/config/config.go, cmd/kwild/config/flags.go, internal/sql/pg/db.go, internal/sql/pg/repl.go, internal/sql/pg/trigger_repl1.sql
- Exposes TrustPeriod flag for snapshots and changes the default value to 36000 hrs
- Fixes the replica identity issue 
- added commit stats debug logs.
=> Preview stats log

cmd/kwil-admin/nodecfg/toml.go, cmd/kwild/config/config.go, cmd/kwild/config/config_test.go, cmd/kwild/config/default_config.toml, cmd/kwild/config/flags.go, cmd/kwild/config/test_data/config.toml, cmd/kwild/server/build.go
Forgot to add the config.toml support in the earlier pr, adding it here.
=> [preview] Support TrustPeriod config in config.toml

cmd/common.go, cmd/kwild/config/flags.go, cmd/kwild/server/build.go, common/config/config.go
Applies https://github.com/kwilteam/kwil-db/pull/1064/files to main
=> added max db connections config

internal/sql/pg/repl.go, internal/sql/pg/repl_msgs.go
backports https://github.com/kwilteam/kwil-db/pull/1071 to release v0.9
=> pg: recognize streaming prepared tx msg (#1071)

internal/engine/generate/actions_test.go, internal/engine/generate/plpgsql.go
cherry-picks https://github.com/kwilteam/kwil-db/commit/2f8259ddce9947973cf1ab8e05fa43b026f83260
=> engine/generate: fix repeated numbered arg typecast (#1076)

build/package/docker/postgres.dockerfile, common/sql/sql.go, common/sql/sql_test.go, internal/abci/abci.go, internal/sql/pg/query.go, internal/sql/pg/tx.go
Backports https://github.com/kwilteam/kwil-db/pull/1079 to `release-v0.9`
=> [release-v0.9] sql,pg: catch db backend failure

internal/engine/generate/actions_test.go, internal/engine/generate/plpgsql.go
Cherrypicks https://github.com/kwilteam/kwil-db/commit/2f8259ddce9947973cf1ab8e05fa43b026f83260
=> [release-v0.9] engine/generate: fix repeated numbered arg typecast

cmd/kwil-cli/csv/csv.go, cmd/kwil-cli/csv/csv_test.go, cmd/kwil-cli/csv/json.csv
Adds tests for CSV JSON parsing. Also fixes a bug where csv column headers weren't being trimmed properly.
=> fix csv parsing issue

README.md
Seems the banner got moved in the refactor.
=> fix missing banner

app/node/build.go, node/node.go, node/peers/peers.go
More shutdown fixes following https://github.com/kwilteam/kwil-db/pull/1130, but in Node and server.
=> fix node shutdown issues

.gitignore, app/key/cmd.go, app/key/file.go, app/key/file_test.go, app/key/gen.go, app/key/info.go, app/node/node.go, app/setup/testnet.go, config/config.go, config/config_test.go, core/crypto/crypto.go, core/crypto/crypto_test.go
This resolves https://github.com/kwilteam/kwil-db/issues/1115 and https://github.com/kwilteam/kwil-db/issues/1116.
=> app,config: define node key file and update cmds

app/node/prof.go, app/node/start.go, config/config.go
This adds the Go pprof system back.  Resolves #1152
=> add go pprof capabilities

testing/testing.go
replaces https://github.com/kwilteam/kwil-db/pull/1181
=> testing: added waiting for testcontainer logs

testing/proxy/proxy_test.go, testing/testing.go
Applies https://github.com/kwilteam/kwil-db/pull/1184 to release v0.9. Also fixes some other compile bugs that were not caught due to build tags
=> testing: added log waiting

testing/testing.go
Alternative to https://github.com/kwilteam/kwil-db/pull/1182 that is more robust. It reads logs to know when it is ready.
=> wait for logs in tests

cmd/kwil-cli/cmds/utils/test.go, testing/testing.go
Apples https://github.com/kwilteam/kwil-db/pull/1191 to release v0.9
=> hoisted pg connection config in testing [v0.9]

cmd/kwil-cli/cmds/utils/test.go, testing/proxy/proxy_test.go, testing/testing.go
Applies https://github.com/kwilteam/kwil-db/pull/1191 to main
=> hoisted pg connection config in testing [main]

app/node/build.go, cmd/kwil-cli/cmds/database/call.go, extensions/precompiles/actions.go, node/engine/errors.go, node/engine/interpreter/context.go, node/engine/interpreter/extension.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go, node/engine/interpreter/planner.go, node/engine/interpreter/schema.sql, node/engine/interpreter/sql.go, node/engine/interpreter/sql_test.go, node/engine/interpreter/values.go, node/voting/events.go, node/voting/vote_test.go, node/voting/voting.go, testing/testing.go
This PR has three bug fixes:
- It fixes an issue where composite constraints cause our info queries to fail
- It fixes an issue where extensions don't have access to account and validator stores when they should (they were simply nil)
- It fixes an issue in the CLI when executing an action
It also includes one new addition to extensions: `OnStart`, which is like `Initialize`, but has access to the engine.
=> fixed gavins feedback

node/voting/voting.go
=> fixes the votestore init issue

common/common.go, core/types/data_types.go, core/types/decimal/decimal.go, core/types/decimal/decimal_test.go, node/engine/errors.go, node/engine/interpreter/context.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go, node/engine/interpreter/ops.go, node/engine/interpreter/planner.go, node/engine/interpreter/schema.sql, node/engine/interpreter/sql_test.go, node/engine/interpreter/values.go, node/engine/interpreter/values_test.go, node/engine/planner/logical/planner.go, node/engine/planner/logical/planner_test.go, node/engine/planner/optimizer/pushdown_test.go
This PR starts some initial work on better testing of the info schema. It also fixes a bug that @Yaiba is blocked on, where numeric precision and scale are not being handled properly.
I will finish the tests in a subsequent PR
=> Engine testing

core/types/data_types.go, extensions/precompiles/values.go, extensions/precompiles/values_test.go, node/engine/errors.go, node/engine/functions.go, node/engine/interpreter/context.go, node/engine/interpreter/extension.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go, node/engine/interpreter/planner.go, node/engine/parse/antlr.go
This PR fixes bugs related to the handling of null values within the engine, as well as adds test coverage.
=> Null handling

common/common.go, extensions/precompiles/actions.go, node/engine/errors.go, node/engine/interpreter/context.go, node/engine/interpreter/extension.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go, node/engine/interpreter/planner.go, node/engine/interpreter/schema.sql, node/engine/interpreter/sql.go, node/engine/interpreter/sql_test.go, node/engine/interpreter/values.go, node/engine/interpreter/values_test.go, node/node_live_test.go, node/services/jsonrpc/usersvc/service.go, node/txapp/routes.go, node/txapp/txapp.go, testing/testing.go
This PR makes a few interface changes for extensions requested by @yaiba. It also registers extension methods as actions.
=> engine: made precompile methods register as actions

cmd/kwil-cli/cmds/database/call.go, cmd/kwil-cli/cmds/database/execute.go, cmd/kwil-cli/cmds/database/message.go, cmd/kwil-cli/cmds/database/query.go, cmd/kwil-cli/cmds/utils/generate_key.go, cmd/kwil-cli/cmds/utils/parse.go, cmd/kwil-cli/cmds/utils/utils.go, core/client/types/client.go, core/crypto/secp256k1.go, extensions/precompiles/actions.go, node/engine/functions.go, node/engine/interpreter/extension.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go, node/engine/interpreter/roles.go, node/engine/interpreter/schema.sql, node/engine/interpreter/sql_test.go, node/engine/parse/errors.go, node/engine/parse/parse.go, node/engine/parse/types.go, test/acceptance/act_test.go, test/acceptance/users.sql, test/expect.go, test/integration/eth-deployer/deployer.go, test/integration/kwild_test.go, test/setup/drivers.go, test/setup/jsonrpc_cli_driver.go, test/setup/jsonrpc_go_driver.go, test/setup/node.go, test/setup/setup_test.go
This was originally meant to be for acceptance tests, but there's something pretty big that I found that we are missing, so putting this up so I can just merge in some of the CLI improvements I've made thus far
=> kwil-cli: improved cli functionality

core/types/results.go, core/types/results_test.go
Changes the interface for scanning according to @Yaiba 's request.
=> update scan interface

config/config_test.go, node/engine/interpreter/context.go, node/engine/interpreter/interpreter.go
=> add better errors

app/shared/display/message.go, core/client/client.go, node/node.go, node/tx.go, node/types/interfaces.go, test/acceptance/act_test.go
Resolves https://github.com/kwilteam/kwil-db/issues/1285
=> node: tx query checks mempool

app/key/cmd.go, app/setup/genesis.go, app/setup/init.go, app/setup/testnet.go, app/shared/display/format.go, app/shared/display/message.go, app/shared/display/table.go, app/validator/join-status.go, app/validator/join-status_test.go, app/validator/list-join-requests.go, app/validator/list-join-requests_test.go, app/validator/list.go, cmd/kwil-cli/cmds/call-action.go, cmd/kwil-cli/cmds/exec-action.go, cmd/kwil-cli/cmds/exec-sql.go, cmd/kwil-cli/cmds/query.go, core/types/types.go
Contains bug fixes and output formatting changes for some `kwild` admin commands
=> kwild: admin command upgrades

app/node/build.go, cmd/kwil-cli/client/roundtripper.go, core/client/client.go, node/node.go, node/services/jsonrpc/usersvc/service.go
The node health check was spectacularly broken.  Fixed here.
=> rpc: fix health check w.r.t. block age

node/engine/interpreter/extension.go, node/exts/erc20reward/meta_extension.go, node/exts/erc20reward/named_extension.go, node/exts/evm-sync/chains/chains.go, node/exts/evm-sync/evm_state.go
Fixes several race conditions and deadlock issues in the erc20 extension.
It is based on https://github.com/kwilteam/kwil-db/pull/1363, so https://github.com/kwilteam/kwil-db/pull/1363 needs to go in first (cc @charithabandi, we don't need you to review this but it is blocked on your review of the other one)
The first commit is https://github.com/kwilteam/kwil-db/pull/1363, the second is what is actually relevant to this PR
=> Fix deadlock

node/mempool/mempool.go, node/mempool/mempool_test.go
This fixes `node/mempool.(*Mempool).RecheckTx` so that it iterates in order.  The previous slice iteration was not working since it modified the slice during iteration, and the subsequent map iteration broke the caller's assumption that it would apply `CheckTx` in order
=> node/mempool: fix RecheckTx again

app/node/start.go, node/engine/interpreter/interpreter_test.go, node/engine/parse/antlr.go, node/engine/planner/logical/errors.go, node/engine/planner/logical/planner.go, node/engine/planner/logical/planner_test.go, node/pg/db_live_test.go
Fixes two issues:
- https://github.com/kwilteam/kwil-db/issues/1386
- https://github.com/kwilteam/kwil-db/issues/1384
=> Engine empty array

cmd/kwil-cli/cmds/call-action.go
resolves https://github.com/kwilteam/kwil-db/issues/1383
=> cli: fix scientific formatting from JSON

common/common.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go, node/node_live_test.go
Adds the ability to admin call the engine.
@Yaiba
=> engine: add CallWithoutEngineCtx

app/setup/genesis.go, app/setup/testnet.go
- Binds network params, chainID and alloc flags to the `setup testnet` command
- Fixes alloc flag parse issue with the 0x accounts.
=> bind network params flags to the testnet init

app/node/node.go, config/config.go, config/config_test.go, contrib/docker/compose/kwil/docker-compose.yml, test/setup/node-compose.yml.template
=> feat(config): expose log rotation config

node/exts/erc20-bridge/erc20/meta_extension.go, node/exts/erc20-bridge/signersvc/kwil.go
This pr fix the nil value handling in bridge client
=> fix(bridge signer): handle nil value from CallWithoutEngineCtx

node/engine/interpreter/context.go, node/engine/interpreter/interpreter.go
Fixes the end block hot path mentioned in https://github.com/kwilteam/kwil-db/issues/1446
Also slightly reworks the existing interpreter cache. There was a way in which it could bloat infinitely, so I had it use an LRU.
=> use lru cache to avoid endblock hot path

node/node.go
This is the proper fix (I believe) for the external address issue.
=> node: fix external address handling again

.github/workflows/manual-test-integration.yaml
This pr fix issues running integration test in CI
=> ci: fix integration test

node/exts/erc20-bridge/erc20/meta_extension.go, node/exts/evm-sync/instance.go
Fixes an issue where we would modify application state on startup within the erc20 bridge. This state change has been moved to occur when the first `USE` is called for a bridge.
=> bridge: fix improper topic register on startup

node/engine/functions.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/interpreter_test.go
=> engine: add greatest, least, nullif

node/engine/README.md, node/engine/interpreter/context.go, node/engine/interpreter/interpreter.go, node/engine/interpreter/planner.go
Adds a basic README to the engine for future maintainers
=> add readme to engine

node/engine/interpreter/interpreter_test.go, node/engine/planner/logical/planner.go
Resolves https://github.com/trufnetwork/kwil-db/issues/1503
CC @outerlook
=> engine: fix bug on partial INSERT ... SELECT

node/snapshotter/resumable_test.go, node/statesync.go, node/statesyncer.go
=> fix: address golangci-lint issues

testing/proxy/proxy_test.go, testing/proxy/seed_1.sql, testing/testing.go
In [this](https://github.com/trufnetwork/kwil-db/commit/79d66da7f16950eaabfb285480ce05b676df0173) commit there was introduced testing framework better handling. But the implementation has issues:
1) In some cases errors are not shown properly
2) No fail if we expect an error but it was not occurred 
This PR fixes the issues.
=> testing: show errors in all use cases, handle use case when an error

core/utils/system.go, node/statesyncer.go
Improves observability of kwild node state sync by adding progress logging for database restoration operations.
**Solution**: Add informative logging that shows restoration progress, size estimates, and completion status to add observability to the state sync process.
**Real World Output**:
```log
...
2025-06-03 12:20:54.430 [INF] STATESYNC: Received snapshot chunk {height=40000 index=50 provider=12D3KooWAfCxVs6Q9KWsABjMiL4Wayq4fAvJFUrGDAK1xrdYZ3vu}
2025-06-03 12:20:54.430 [INF] STATESYNC: All chunks downloaded successfully {total_chunks=52}
2025-06-03 12:20:54.430 [INF] STATESYNC: Restoring database from snapshot. This may take a while, please do not interrupt the process. {size=779.4 MB chunks=52 cpu_cores=4 os=linux estimated_time=~11 minutes}
2025-06-03 12:20:54.430 [INF] STATESYNC: …
```
=> chore: improve StateSync logs
