- .github/workflows/ci.yaml
- cmd/kwild/config/config.go
- deployments/compose/postgres/Dockerfile
This updates our extended postgres Dockerfile so that it inserts an init script to create the "kwild" superuser and a "kwild" database owned by that user.  We can do other init tasks in these files, and can also include arbitrary .sh scripts to customize further.
This also changes the default `app.pg_db_host` to `127.0.0.1` instead of `/var/run/postgres` so that it can work with the Docker images and services without having to specify the hosts.
With this, I have pushed to [`jchappelow/kwil-postgres:latest` on Docker Hub](https://hub.docker.com/r/jchappelow/kwil-postgres/tags), and we can do:
```sh
docker run -v /home/jon/kwil-pg-test:/var/lib/postgresql/data -p 5432:5432 \
-e "POSTGRES_PASSWORD=kwild" jchappelow/kwil-postgres
```
Qs:
- is this a resolution for the quickstart?
- Can we …
> deployments,config: further extend postgres Docker, default to 127.0.0.1

- test/acceptance/helper.go
- test/integration/helper.go
This pr change the behavior to do nothing when test cleanup, to avoid the anecdotal network jitter issue https://github.com/kwilteam/kwil-db/actions/runs/8057247286/job/22008434691#step:24:209
We now have `Prune Docker` step in CI so it's also redundant.
BTW, originally I want to solve this problem by running all tests in one network, after I got some wired bugs I realized I cannot do it that way, since we use `nodeX`(dns name) to reach out different node, in same network those dns will change in parallel mode very often/quick, leading to network issue.
> try fix test network jitter

- deployments/compose/kwil/docker-compose.yml
- internal/txapp/txapp.go
Voters/Validators is one good indicator of whether we are using stale pg instance or a new instance as we always initialize voters in the genesis. So using that to do sanity checks at the genesis.
> PG Sanity checks at Genesis 

- cmd/kwil-admin/cmds/setup/cmd.go
- cmd/kwil-admin/cmds/setup/genesis-hash.go
- cmd/kwil-admin/cmds/setup/reset.go
- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/folders.go
- cmd/kwild/config/genesis.go
- cmd/kwild/config/reset.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/server.go
- docs/sql/README.md
- internal/engine/ddl/index.go
We don't support genesis-hash computation with postgres yet. Disable the command.
Also fix the reset command so it does not try to delete the old sqlite path, which no longer exists.
Finally, clean-up old SQLite mentions and example configs.
> kwil-admin,config: disable genesis-hash command

- .github/workflows/ci.yaml
- Taskfile.yml
- test/integration/helper.go
This fix the issue running integration test locally in parallel mode:
- increase default testcontainer wait timeout to 20s
- use correct test flag `parallel` to control the maximum number of tests to run simultaneously
- no parallel number control on CI, since CI machine is more powerful, and we expect test to finish asap
> fix integraion test locally parallel issue

- core/rpc/client/gateway/http/client.go
This pr fix the gateway error message, it will try to output error detail returned by gateway
Before:
```
Do you want to sign this message?: y
authentication failed: gateway auth: not found
401 Unauthorized
```
After:
```
Do you want to sign this message?: y
authentication failed: gateway auth: invalid signature
```
**NOTE**: this should be back-ported to v0.6
> fix gateway client auth error

- .github/workflows/ci.yaml
- Taskfile.yml
- go.mod
- go.sum
- internal/version/version.go
- test/go.mod
- test/go.sum
In preparation for a release version with importable packages and go install'able applications, this removes the `replace` directives from the main module's go.mod.
This also removes the replace directives from the `test` module so that it tests what is actually built, not just what is in the git workspace.
With the replaces removed from the go.mod files, development on `release-v0.6` branch may require a go.work with `replace` directives in it.  However, if a build fails or CI fails without any replaces in go.mod or a go.work, that indicates we probably have to tag either the `core` or `parse` submodules and then update the main module's go.mod `require` on it.
> [release-v0.7] deps: remove replace directives and tests in non-workspace mode

- cmd/kwild/main.go
- cmd/kwild/root/root.go
I've moved the root `kwild` cobra command out of `main`, into its own module.
For users building extensions, we are able to have them simply import this, instead of needing them to fork the whole repo. Teams like Truflation can do:
```go
package main
import (
"fmt"
"os"
"github.com/kwilteam/kwil-db/cmd/kwild/root"
)
func init() {
// register extensions
}
func main() {
if err := root.RootCmd().Execute(); err != nil {
fmt.Println(err)
os.Exit(1)
}
os.Exit(0)
}
```
and then simply run:
```shell
go build ./main.go
```
This is substantially easier than cloning the repo. We have found cloning to be quite intimidating, and a source of confusion with the Truflation team.
> moved root command for easier building

- core/gatewayclient/client.go
- core/gatewayclient/msg.go
kwilteam/kgw#18
This add support for kgw cookie prefix for https. 
NOTE: This needs to be back ported to v0.6.6
> kgw: handle __Host- prefix in https

- .goreleaser.yaml
This pr fix goreleaser config, by default all release will be a draft.
> update go releaser conf

- .goreleaser.yaml
- cmd/kwild/server/build.go
- cmd/kwild/server/utils.go
- internal/abci/abci.go
As discussed in Slack, I have removed the circular imports between abci and cometbft. We now simply will:
a. not propose a block if the local node is not a validator in the application
b. reject blocks proposed by nodes that the application does not recognize as validators
> removed circular abci import

- .github/workflows/ci.yaml
Since we switch back to github's public runner, we no longer have access to the logs for failed test case.
This pr tries to print error if a step fails, by just `grep` the log files
> CI: add print error step

- internal/txapp/errors.go
- internal/txapp/routes.go
Resolves at least some of https://github.com/kwilteam/kwil-db/issues/582
I need to manually test these negative paths, but these seem to be the most apparent missing checks.
> txapp: is/not validator checks

- .github/workflows/ci.yaml
- cmd/kwil-admin/nodecfg/generate.go
- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwil-admin/nodecfg/toml_test.go
- cmd/kwild/config/config.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/root/root.go
When doing `--autogen`, write out the `config.toml` from the generated configuration.
Also, in autogen mode, change the default `HTTPListenAddr` to all interfaces rather than localhost.  I've kept the default in  other cases at `localhost:8080`.  This adds a little more logic.
Testing in `deployments/compose/kwil`:
```
kwild-single           | Root directory "/app/.kwild"
kwild-single           | Private key path: /app/.kwild/private_key
kwild-single           | Generated new private key, path: /app/.kwild/private_key
kwild-single           | Generated new genesis file: /app/.kwild/genesis.json
kwild-single           | Writing config file to /app/.kwild/config.toml
```
> config,nodecfg: write out config file in autogen mode

- internal/sql/pg/repl.go
- internal/sql/pg/replmon.go
Untracked transaction are intended to have a sequence number of -1, indicating there was no sequence update, which is used by transactions from a `pg.DB` instance to correlate WAL data updates with a certain transaction.
This commit fixes the replication monitor to work correctly with _concurrent untracked transactions_ by, such as those from the event store:
- reset the `seq` var to -1 in the `captureRepl` loop after each commit
- when a commit is reached with `seq` still -1 (not updated by an untracked transaction), do NOT send the commit ID on the channel
This also beefs up the logging and error handling in unexpected cases, which corresponds to improper use of `replMon` methods or concurrent (ab)use of the sentry table to break correct transaction sequencing.
@charithabandi Pls rebase …
> pg: reset seq num in replication after commit msg

- internal/sql/pg/repl_test.go
- test/acceptance/test-data/test_db.kf
This updates the acceptance test's kf scheme with a call to a `delete_user` action so that we can ensure it does not fail by incorrectly parsing as and SQL statement.
The acceptance test fails at `v0.7.0-rc.1` with: `deploy_database.go:15: cannot parse database schema syntax error: line 1:0 "mismatched input 'delete_user' expecting {<EOF>, ';', 'DELETE', 'INSERT', 'SELECT', 'UPDATE', 'WITH'}" (with 1+ errors): delete_user();`
> test: include nested delete action call

- core/client/tx.go
- test/stress/db.go
- test/stress/hammer.go
- test/stress/harness.go
- test/stress/main.go
This updates the stress tool with:
- a "nonce chaos" (`-nc`) option to apply a random jitter to the correct nonce at a rate of 1/nc times.
- When using the `create_post` action, create action call transactions that intentionally fail execution with incorrect argument count or types.  This ensures nonce and balance updates happen regardless of the execution outcome (tx code), and that the node is resilient to failures in user SQL queries as well as the engine's handling of procedure call errors.
This also fixes a bug in `core/client.Client` where the `WithFee` option was ignored.  This is not critical since kwil-cli does not use it like it does the `WithNonce` option from `--nonce`, but I did want to have the stress tool do unexpected things with the `tx.Body.Fee` field and I realized this …
> stress,client: nonce chaos and failed execution options

- cmd/kwild/server/cometbft.go
- internal/abci/abci.go
- internal/abci/cometbft/genesis.go
- internal/abci/cometbft/node.go
`kwild` has it's own config.toml and genesis.json files, each with fields and formats that differ from cometbft's.  When we launch a cometbft `Node` we supply the translated configs in-memory.
This change writes out cometbft's version of these files, which reflect the effective config given to the node.  They are written into `<root_dir>/abci/conf`, where `<root_dir>/abci` is considered the cometbft "home" directory.  This helps debug, but more importantly it allows the use of the `cometbft` command-line tool for commands like `inspect` and `rollback`:
```
$  cometbft rollback --hard --home ~/kwil/git/kwil-db/cmd/kwil-admin/.testnet/node0/abci
Rolled back both state and block to height 823 and hash 5C9824172FF1717C32671420A02E76B41779687A7642F3A19D9B5A56ACF3278F
```
```
$  cometbft …
```
> abci,kwild: write in-memory cometbft confs to disk for inspect

- common/testdata/procedures.go
- common/testdata/schema.go
- extensions/precompiles/actions.go
- internal/engine/execution/dataset.go
- internal/engine/execution/execution_test.go
- internal/engine/execution/global.go
- internal/engine/execution/procedure.go
This resolves a bug with the handling of deeply nested action calls. Ultimately the fix may be a gas cost for each action call, possibly exponentially increasing with depth, but I think a hard limit is still a good idea when user-defined recursion is a possibility.  See code comments for more.
I don't think we want to scheme authors to write recursive algorithms, but if we change our mind I think we can life this restriction.
> engine: create a max procedure call stack depth

- cmd/kwild/root/root.go
- cmd/kwild/server/build.go
- cmd/kwild/server/server.go
- internal/abci/cometbft/node.go
- internal/sql/pg/db.go
- internal/sql/pg/repl.go
- internal/sql/pg/repl_test.go
- internal/sql/pg/replmon.go
This resolves the shutdown triggered appHash mismatch I have been observing.  It also resolves some shutdown sequence issues that led to the issue.
@charithabandi's debugging lead to identifying these issues and their fixes. Thanks so much!
In short, we were pulling the plug on parts of the DB subsystems before killing cometbft's node.  Also, we actually didn't have a way to stop the node's replay process before, but now we are using `NewNodeWithContext`.  Also, the `pg` package now does not shutdown the replication monitor goroutines on global context cancellation, only the connection establishment functions.  It now correctly stops the goroutines where it was intended in the `Close` method.
> server,pg: fix shutdown sequence

- internal/txapp/mempool.go
- internal/txapp/txapp.go
If there is a ValidatorVoteID transaction, mark the voteIDs for rebroadcasting only on the issuer's node. Currently all the nodes would mark the ids as rebroadcast.
> Mark rebroadcast only on the voteID Tx issuer

- core/rpc/client/user/http/error.go
The issuse: when kwil-cli request a provider, error detail is not avaliable for kgw response.
Since both kwild and kgw requests are handled by same http client, and for now they have different error response(#623 try to fix this)
This pr change the `parseErrorResponse` function, to support kgw error response.
The output(mocked):
before
```
$ .build/kwil-cli database call --action owner_only --name testdb --kwil-provider http://localhost:8090 --authenticate
error calling action: call action: 400 Bad Request
err code = 0, msg =
$ .build/kwil-cli database call --action owner_only --name testdb --kwil-provider http://localhost:8080
error calling action: call action: 400 Bad Request
err code = 3, msg = mock call bad request error
```
after 
```
$ .build/kwil-cli database call --action …
```
> [v0.7.2] core: fix parse kgw error, so it output detailed message

- .github/workflows/ci.yaml
- .github/workflows/kgw-test-reuse.yaml
- .github/workflows/main.yaml
- .github/workflows/manual-test-kgw.yaml
- .github/workflows/release.yaml
- .github/workflows/trigger-test-kgw.yaml
As there are:
- permission issue running kgw test in PRs from forked branch
- privacy/security issue since kgw is private repo
Running kgw test on main branch seems a way to do it, as by the time it's merged to main, it's reviewed. And also (seems) no permission issue.
The `main` workflow tries to load the kwild image from cache built from `ci` workflow, then build kgw image and run only the kgw integration tests.
I'm doing experimenting rn. Not ready for review yet.
> [WIP] CI: try kgw test on main branch update

- cmd/kwil-admin/cmds/validators/list.go
fix minor typo for `validators list-validators` command
> kwil-admin: fix minor typo

- cmd/kwild/config/config.go
- cmd/kwild/config/config_test.go
- cmd/kwild/server/build.go
- cmd/kwild/server/cometbft.go
- cmd/kwild/server/cometbft_test.go
- core/utils/url/url.go
- core/utils/url/url_test.go
- test/driver/cli_driver.go
Rebirth of https://github.com/kwilteam/kwil-db/pull/527
This allows the listen addresses for app gRPC and HTTP to be partially specified, with only one of port or host, in which case it will use the default parsed from the full default listen address.
A similar change is applied for the cometbft listen addresses, but also applying the default scheme since cometbft requires a fully qualified URL with scheme unlike our apps listeners.
> kwild,utils/url: allow using default port or host

- .github/workflows/release.yaml
The release workflow runs on 'created' and 'published' type.
Based on https://github.com/kwilteam/kwil-db/actions/workflows/release.yaml, we don't need 'created' trigger type.
Two reasons:
- 'created' won't be triggered for a draft release
- - we configured goreleaser to create 'draft' release by default.    Cannot create non-draft, non-pre-release, non-latest-release through gorelease.
- - it'll trigger twice if we created a non-draft release directly.
- 'published' will be triggered by 'pre-publish', so we can turn 'draft' to 'pre-release' to run the test, if test pass, turn it into 'latest-release'
> ci: only trigger release workflow on 'published'

- .github/workflows/manual-test-kgw.yaml
This pr allow a sha to checkout for kwil-db repo, it's useful for PR from forked branch(kwil-db)
> ci: allow manual test kgw with sha

- .github/workflows/kgw-test-reuse.yaml
- .github/workflows/release.yaml
This backports KGW test in release workflow(#626 and #631), so v0.7 release will trigger KGW test.
From https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release, it will checkout to `Tag ref of release refs/tags/<tag_name>`, so we need this workflow on release-v.07
> [v0.7.2] ci: test kgw in release workflow

- core/rpc/client/gateway/http/client.go
This update gateway client to be compatible with new kgw repsonse structure, which is compatible with swagger error response
This requires both kwil-cli and kgw update
This should be merged once after kwilteam/kgw#29 is merged
> core: gateway response change

- cmd/kwild/server/server.go
- extensions/listeners/eth_deposits/deposits.go
- extensions/listeners/eth_deposits/ethereum.go
- internal/listeners/mgr.go
- internal/txapp/txapp.go
- test/cmd/ethlisten/.gitignore
- test/cmd/ethlisten/main.go
- test/integration/eth-deployer/deployer.go
- test/integration/helper.go
- test/integration/kwild_test.go
This PR resolves a few sticky issues with the eth oracle listener and eth rpc client.
- `retry()` is now cancellable so listener stop doesn't result in reconnect loop. The validator add/remove test with oracles enabled often resulted in this case.
- also use `ethclient.DialContext` (instead of `ethclient.Dial`) to cancel hung (re)connects
- re*connect* logic is left to the go-ethereum RPC client, which has automatic reconnect built-in.  The removed reconnect code was also duplicated in three separate spots.
- In the `ListenToBlocks` loop with `select`, use a `time.Ticker` instead of doing `case <-time.AfterFunc(d)`, which leaks timers since in the healthy state blocks will be the `case` that hits first.
- make `SubscribeValidators` method of `TxApp` to avoid polling `GetValidators` every …
> listeners,eth_deposits: eth client reworking

- core/rpc/client/function/http/client.go
- core/rpc/client/user/http/client.go
The generated Swagger http clients require a URL to which an method's endpoint path is appended.  This is a problem if this base path has a trailing slash since the endpoint paths begin with a slash. The result is that kwild's server will report 404 not found, while kgw would try to clean the path but redirect with GET even for POST.
This change fixes our http client constructors to trim trailing slashes from the base URL.
> http: strip trailing slashes from "BasePath"

- core/rpc/client/function/http/client.go
- core/rpc/client/user/http/client.go
The generated Swagger http clients require a URL to which an method's endpoint path is appended.  This is a problem if this base path has a trailing slash since the endpoint paths begin with a slash. The result is that kwild's server will report 404 not found, while kgw would try to clean the path but redirect with GET even for POST.
This change fixes our http client constructors to trim trailing slashes from the base URL.
> [v0.7.2] http: strip trailing slashes from "BasePath"

- core/gatewayclient/client.go
> [v0.7.2] gatewayclient: fix domain compare when match cookie

- go.mod
- go.sum
- test/go.mod
- test/go.sum
AFAIK, this is the final step for `v0.7.2`
Reminder: there are no `replace` statements in releases, so this tag-then-update-dependents flow is needed.
> [v0.7.2] use core/v0.1.2 for release

- test/acceptance/kwild_test.go
This remove the code enable gas by default for `task dev:up`, if needed, we can set `KACT_GAS_ENABLED` env var to enable this on demand
> test: remove hard code gas enable for 'task dev:up'

- core/gatewayclient/client.go
- core/types/gateway/gateway.go
This applies authn precheck logic.
It is done by KGW https://github.com/kwilteam/kgw/commit/c10a50d009ee293a02988ec3f7e911da51fca4a3 returns extra domain/chainID/version info that it uses for composing message and verify signature. gateway client here will check if those are same before do the signing.
An example output:
```
$ .build/kwil-cli database call --action owner_only --name testdb --kwil-provider http://127.0.0.1:8090/ --authenticate
http://127.0.0.1:8090/ wants you to sign in with your account:
I accept the Terms of Service: https://yourdoamin.com/tos
URI: http://127.0.0.1:8090/auth
Version: 1
Chain ID: kwil-test-chain
Nonce: 4bf1ca947380742134e3
Issue At: 2024-04-12T16:45:32Z
Expiration Time: 2024-04-12T16:46:02Z
Do you want to sign this message?: y
error calling action: …
```
> core: gateway client authn precheck

- internal/txapp/txapp.go
Adds a debug log for failed resolutions. We should backport this to v0.7, since it will be helpful for @outerlook who is implementing the Streamr oracle for Powerpod
> added debug log for expired resolutions

- build/package/docker/postgres.dockerfile
This removes the wal sender timeout, which is not helpful for kwild's application:
- https://bugzilla.redhat.com/show_bug.cgi?id=1342255
- https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html
- https://www.postgresql.org/docs/current/runtime-config-replication.html
> docker: no wal sender timeout in postgres image

- core/rpc/client/error.go
- core/rpc/client/function/http/client.go
Return a wrapped error in `VerifySignature`, so an app can easily distinguish communication error from server logic error.
A example in kgw https://github.com/kwilteam/kgw/blob/023575d8605fa3e1ddc8d48cb3a8953b57b5430e/utils.go#L149, kgw naively just does string match to determine if it's a server logic error. But for authenticator related errors, this won't work.
This should be backported to v0.7 and v0.6
> function client: VerifySignature return wrapped error

- internal/txapp/txapp.go
- internal/voting/sql.go
- internal/voting/vote_test.go
- internal/voting/voting.go
There is an issue with `FilterExistsNoBody` which is supposed to take list of event IDs and filter out the events/resolutions to which we already received a voteBody. But the API filters out only the ids for which the resolution and body exists. It doesn't return the event ids to which the resolutions are not created yet. This becomes more pronounced in a single-node deployments as we only do voteBody Transactions, so resolutions without body are never created, Essentially the extensions will not work in a single-node deployments.
> VoteBodyTx fixes

- core/rpc/client/error.go
- core/rpc/client/function/http/client.go
This backports #673 to v0.7.
I guess we put this in v0.7.4?
core version should be bumped as well
> [v0.7.4] func client wrap error

- internal/services/grpc/txsvc/v1/convert.go
Fixes the bug mentioned here: https://github.com/truflation/tsn-data-provider/issues/58#issuecomment-2077994594
The Truflation team noticed that schema extensions were not properly being returned from the txsvc
> return schema from http server

- cmd/kwil-cli/cmds/account/balance.go
- cmd/kwild/server/utils.go
- internal/abci/abci.go
- internal/services/grpc/txsvc/v1/broadcast.go
- test/driver/cli_driver.go
This is https://github.com/kwilteam/kwil-db/pull/680, but for `main` and also with warning logged in `prepareBlockTransactions` if a transaction is held back for exceeding the block size limit (which is only likely in the case of lots of validator inserted txns).
> tx broadcast debugging

- .github/workflows/ci.yaml
- deployments/compose/kwil/docker-compose.yml
- deployments/compose/postgres/docker-compose.yml
- test/acceptance/docker-compose-dev.yml
- test/acceptance/docker-compose.yml
- test/integration/docker-compose-dev.yml
- test/integration/docker-compose.yml.template
With the `kwildb/postgres` docker image updated in https://github.com/kwilteam/kwil-db/pull/605, this updates the CI to use that version explicitly.
Also use `postgres:16.2` in the compose service files, and update the command flags to match `kwildb/postgres:16.2-1`.
> docker: use 16.2 in compose

- cmd/kwil-cli/cmds/common/roundtripper.go
- cmd/kwil-cli/cmds/configure/configure.go
- cmd/kwil-cli/cmds/utils/message_test.go
- cmd/kwil-cli/config/config.go
- cmd/kwil-cli/config/flags.go
- test/driver/cli_driver.go
BREAKING CHANGE:
- change flags `kwil-provider` to `provider`
- change config field `grpc_url` to `provider`
- change default config folder from `~/.kwil_cli` to `~/.kwil-cli`
> change kwil-cli config and flags 

- .github/workflows/ci.yaml
- .github/workflows/kgw-test-reuse.yaml
- Taskfile.yml
- parse/kuneiform/parser_test.go
This re-enables unit tests and mod tidy for the reborn `parse` module.
On doing so, there is a failing unit test (`Test_Parse/all_possible_constraints` in `parse/kuniform`):
```
--- FAIL: Test_Parse (0.00s)
--- FAIL: Test_Parse/all_possible_constraints (0.00s)
parser_test.go:505: 
Error Trace:	/home/jon/kwil/git/kwil-db/parse/kuneiform/parser_test.go:505
Error:      	Received unexpected error:
parent table other_uses not found
Test:       	Test_Parse/all_possible_constraints
```
I've updated parse/kuneiform/parser_test.go with a make-it-pass mindset, but this is a very naive resolution.  I'm not sure why this test passed before or what the correct resolution is.  I do recall that the `Clean` methods now take a list of tables, which I think is for typing, but I'm not positive.  @brennanjl …
> parse,tasks: reenable parse unit tests and tidy

- internal/engine/execution/global.go
- internal/sql/pg/query.go
```
Named (in postgres) prepared statements can fail if the table
definitions later change.  Since the default query mode creates and
persists them, query can fail unexpectedly, requiring a retry.
The mode QueryModeExec prevents this issue by not creating named
prepared statements that can become invalid.
This change uses the same query mode used by action call/execution to be
used for ad hoc queries.
This also adds the QueryModeDescribeExec mode to the QueryMode
enumeration since it may be a better default in other cases, perhaps
for kwild in the future.  This is because it does not have the
undesirable named statement behavior, but it can still rely on postgres'
Parse/Describe protocol to do argument type determination. The down side
of this mode is that it requires two round trips, …
```
> engine,pg: fix ad hoc query prepared statement

- cmd/kwild/config/config.go
- cmd/kwild/root/root.go
Env variables are not supported since we renamed the cmd line flags to have hyphens or dashes instead of underscores. Whereas the struct tags remained to use dashes to support config file parsing. Therefore manual binding is needed to map the env variables correctly to the structures.
> # Load env variables into KwildConfig

- cmd/kwild/config/config.go
- cmd/kwild/root/root.go
Cherry-pick https://github.com/kwilteam/kwil-db/pull/705
> [v0.7.5] Load env variables into KwildConfig

- .github/workflows/backport.yml
This add backport workflow.
Requirements:
How to: tag the PR you want to backport, it always starts with `backport-to-BRANCH`. So if we want to backport to v0.7, the tag will be `backport-to-release-v0.7`. After tagged PR is merged, a backport pr will be created automatically.
---
UPDATE: a demo
https://github.com/Yaiba/test-relase-based-workflow/pull/9, this is the original pr;
after applying label backport-to-release-v0.1 to the pr,  once it’s merged, it creates a new pr https://github.com/Yaiba/test-relase-based-workflow/pull/10
> ci: add backport workflow

- .github/workflows/backport.yml
I've update kwilteam/backport-github-action https://github.com/kwilteam/backport-github-action/commit/b3eae3fb1be75da400e9d7094282dfcd9bc6ffa1 so it has https://github.com/sorenlouv/backport/pull/493 merged, should have multi commits backport issue fixed
> ci: fix multi commits backport

- .github/workflows/backport.yml
This add a condition on backport action, so it only runs when pr is merged and has a label like `backport-to-`
> ci: backport with condition

- .github/filters.yaml
- .github/workflows/backport.yml
- .github/workflows/ci.yaml
- .github/workflows/kgw-test-reuse.yaml
- test/acceptance/kwild_test.go
- test/integration/kwild_test.go
As our CI running time is now taking average 25 mins, we need to offload some unnecessary CI runs.
This add path filter to skip CI on certain file changes.
We use https://github.com/dorny/paths-filter, as the builtin [path filter](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) won't fit in our use case
> skip CI on some file changes

- go.mod
- go.sum
- internal/version/version.go
- test/acceptance/kwild_test.go
- test/go.mod
- test/go.sum
This pr is going to update go.mod which deps on core/v0.1.3(to tag, I'll tag it once I'm sure no more changes will be made to core module).
> [v0.7.5]  update gomod for core module version bump

- core/types/schema.go
@KwilLuke commented on inconsistencies for nulls in JSON marshalled schemas. This PR removes `omitempty` tags to make the marshalling consistent.
We sort've used these randomly so I figured it's not a big deal to just ditch them
> made schema null marshalling consistent

- cmd/common/display/message_test.go
- core/rpc/json/commands.go
- core/rpc/json/function/func.go
- core/rpc/json/responses.go
- core/types/transactions/transaction.go
- core/types/transactions/transaction_test.go
- core/types/types.go
The Fee field of `core/types/transactions.TransactionBody` is a `*big.Int`.  By default this marshals to/from an integer (json number).  This should be a string to avoid issues with JavaScript representing all numbers as 64-bit floating point values, which can't store a large int64 (same reason why `json.Number` exists in Go).
This also changes a few field types:
- `TxQueryRequest.TxHash` is now `HexBytes`
- `TxQueryResponse.TxHash` is now `HexBytes`
- `BroadcastResponse.TxHash` is now `HexBytes`
- `VerifySignatureRequest.Msg` is now a `[]byte` (not `HexBytes`)
Finally, remove `core/types.NodeInfo`, which was unused (there's something similar that is used in core/types/admin).
> transactions: fix fee marshaling

- cmd/common/display/message.go
- cmd/common/display/message_test.go
- cmd/kwil-admin/cmds/utils/query-tx.go
- cmd/kwild/server/build.go
- cmd/kwild/server/utils.go
- core/rpc/client/user/http/client.go
- core/rpc/client/user/jsonrpc/methods.go
- core/types/transactions/result.go
- internal/abci/abci.go
- internal/services/jsonrpc/usersvc/service.go
Performance showed that polling TxQuery frequently can lead to resource saturation due to computation of Hash() for all the transaction in the mempool. This PR avoids this by ABCI computing the TxHash when it first sees the transaction through CheckTx and stores it in its internal structure. This hash would be purged once the tx is included in the block. This avoids repeated computation of the Hash() in the TxQueries. 
Also reduces the repeated hash computations in checkTx making them a tad bit faster. 
One major change in the TXQuery behavior is the result doesn't include the actual transaction if its in the mempool, as we currently don't have a way to retrieve it without computing and checking the Hashes of all the mempool transactions. I am gonna raise a issue with cometBft to expose …
> Optimize TxQuery

- cmd/kwild/server/utils.go
This fixes the "syncing" field of the node status response always being false.
This change sets it from the "CatchingUp" field of the response from cometbft's `Status` RPC (local client).
> kwild: fix cometbft client not setting "syncing"

- cmd/common/display/message.go
- cmd/common/display/message_test.go
- cmd/kwil-admin/cmds/utils/query-tx.go
- cmd/kwil-cli/cmds/utils/decode.go
- cmd/kwil-cli/cmds/utils/message.go
- cmd/kwil-cli/cmds/utils/tx_query.go
- cmd/kwil-cli/cmds/utils/utils.go
- core/types/transactions/payloads.go
- core/types/transactions/payloads_test.go
This adds the "utils decode-tx" command to kwil-cli. This is useful with the raw transaction bytes that are currently available from the cometbft RPC server at endpoint `/tx?hash=` or any other source while debugging.
This also adds an `UnmarshalPayload` function to core/types/transactions to allow creating a new instance of a Payload without having to know the concrete type associated with a PayloadType. This allows kwil-cli to easily interpret and display the decoded payload.  If this PR is ported to a release, I'd probably remove this decoding functionality.
deploy:
```
$  ./kwil-cli database deploy -p ~/test_db-nomath.kf --chain-id "" --sync
TxHash: 5307f10f9f6852b7812670aae4ae886a36beb2cbb12ebe1241e986df986eab76
Status: success
Height: 2230
Log: success
```
use cometbft RPC server …
> kwil-cli,transactions: add decode-tx command

- internal/services/jsonrpc/usersvc/service.go
Resolves https://github.com/kwilteam/kwil-db/issues/725
The following rpc service methods calling into engine are now returning the full error when it is unidentified:
- `Query` (this is the most sensible place to return the full engine error)
- `ListDatabases` (but this error is more likely to be genuinely internal, since an empty slice is the result if none found rather than an error)
- `Call` (like `Query` it is likely that the "internal" error will be important to help the user resolve the issue with their call or the dataset definition itself).
Note that `Schema` also uses the `engineError` helper, but `engine.GetSchema` only returns `ErrDatasetNotFound` or `nil`, and there is no internal error that would have been discarded.
> services/jsonrpc: do not throw away engine error details

- internal/txapp/mempool.go
When a transaction is submitted to mempool while gas is enabled, a new account (which has no balance) now has the transaction rejected with an "insufficient balance" error instead of reporting that the account was not found.
Resolves https://github.com/kwilteam/kwil-db/issues/653
> txapp: report insufficient balance for new accounts

- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/build.go
- core/rpc/json/errors.go
- internal/services/grpc/txsvc/v1/call.go
- internal/services/grpc/txsvc/v1/opts.go
- internal/services/grpc/txsvc/v1/query.go
- internal/services/grpc/txsvc/v1/service.go
- internal/services/grpc_server/options.go
- internal/services/grpc_server/server.go
- internal/services/jsonrpc/server.go
- internal/services/jsonrpc/server_test.go
- internal/services/jsonrpc/usersvc/service.go
WIP: looks fine, but need to test e2e.
This adds two timeouts with settings to kwild:
-  `app.rpc_timeout`  --  timeout for the duration of request handling for both gRPC (and thus http gateway) and JSON-RPC servers enforce the timeout. This is a *server timeout*.
- `app.db_read_timeout` -- timeout on read-only DB actions (actually engine, but using the read-only DB tx). This is a *service timeout* applied only in Call and Query methods of the user service.
For gRCP, `rpc_timeout` uses a unary interceptor that cancels the context given to the service method.  If I missed an existing timeout feature in the grpc packages, please let me know.  I feel like this should have already existed.
For JSON-RPC, I thought this was handled by `http.Server.WriteTimeout`, but shockingly that timeout only …
> kwild,rpc: db and rpc timeout settings

- internal/sql/pg/db.go
- internal/sql/pg/tx.go
This fixes a shutdown deadlock and eventual DB reader pool exhaustion while running.
@brennanjl This resolves the hang you observed.  I accidentally reproduced it while testing the timeouts in https://github.com/kwilteam/kwil-db/pull/736
I hate to say it, but this might need to be on `release-0.7`
> pg: always release conn on commit/rollback error

- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/build.go
- internal/services/grpc/txsvc/v1/call.go
- internal/services/grpc/txsvc/v1/opts.go
- internal/services/grpc/txsvc/v1/query.go
- internal/services/grpc/txsvc/v1/service.go
- internal/services/grpc_server/options.go
- internal/services/grpc_server/server.go
- internal/version/version.go
This backports https://github.com/kwilteam/kwil-db/pull/736, just without the JSON-RPC pieces.
> [v0.7.6] kwild,rpc: db and rpc timeout settings

- cmd/kwild/server/build.go
- internal/services/jsonrpc/server.go
This resolves #749
This adds a simple basic CORS returns cors headers for all requests
> feature: support basic cors for jsonrpc server

- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/config_test.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/build.go
- cmd/kwild/server/server.go
- cmd/kwild/server/utils.go
- core/log/logger.go
- internal/abci/cometbft/node.go
This adds the ability to raise the log level threshold for: RPC, cometbft, and DB (pg).  This feature is helpful if you want to do things like:
- run kwild with *debug* level logging, but don't want one of these systems spamming so you can set those to *info*
- run kwild with default *info* level logging, but only want *warnings* (or worse) from cometbft, etc.
I would like the ability to set all subsystem loggers independently, including lowering the threshold, but zap only permits increasing the level for child loggers.  This restriction seems to be a consequence of the zap core architecture.
> log,kwild: allow increase log thresh on child loggers

- common/common.go
- core/rpc/client/user/http/client.go
- core/rpc/client/user/jsonrpc/methods.go
- core/utils/json/json.go
- core/utils/json/json_test.go
- extensions/precompiles/actions.go
- internal/engine/execution/global.go
- internal/engine/execution/queries.go
- internal/engine/generate/plpgsql.go
- internal/services/grpc/txsvc/v1/call.go
- internal/services/jsonrpc/usersvc/service.go
- internal/txapp/routes.go
- parse/contextual.go
- test/acceptance/kwild_test.go
- test/acceptance/test-data/contextual_vars.kf
- test/driver/cli_driver.go
- test/driver/client_driver.go
- test/specifications/contextual_vars.go
- test/specifications/dsl.go
- test/specifications/procedures.go
- test/specifications/schemas.go
Adds @height and contextual variables tests.
This commit adds an @height variable at the request of the Truflation team. It also adds an integration test for testing contextual variables.
Finally, it fixes two bugs. The first one caused SQL generated for actions to not use the `current_setting` postgres function, which caused it to incorrectly read contextual variables. The second bug caused postgres to incorrectly decode the transaction signer, essentially yielding an incorrect signer for the @signer variable.
> Height var

- internal/engine/execution/dataset.go
- internal/engine/generate/plpgsql.go
- internal/engine/integration/procedure_test.go
- parse/antlr.go
- parse/gen/kuneiform_parser.go
- parse/gen/kuneiformparser_base_visitor.go
- parse/gen/kuneiformparser_visitor.go
- parse/grammar/KuneiformParser.g4
- parse/parse_test.go
Fixes https://github.com/kwilteam/kwil-db/issues/763.
Equality operators now use `IS DISTINCT`. See here for explanation: https://stackoverflow.com/questions/36508815/not-equal-and-null-in-postgres.
This pr also fixes an issue where procedure calls that do not receive the correct number of arguments give a confusing postgres error. It now gives a more descriptive error.
Should be merged after https://github.com/kwilteam/kwil-db/pull/765
> Fix null comparison

- Taskfile.yml
- internal/abci/abci.go
- internal/abci/abci_test.go
- internal/abci/interfaces.go
- internal/sql/pg/conn.go
- internal/sql/pg/db.go
- internal/sql/pg/system_online_test.go
- internal/sql/pg/tx.go
- internal/txapp/interfaces.go
- internal/txapp/txapp.go
Resolves https://github.com/kwilteam/kwil-db/issues/755
The gist of the reserved connections is:
```go
// BeginReservedReadTx starts a read-only transaction using a reserved reader
// connection. This is to allow read-only consensus operations that operate
// outside of the write transaction's lifetime, such as proposal preparation and
// approval, to function without contention on the reader pool that services
// user requests.
```
So, some stuff can use `r.currentTx` (the consensus write connection) but in other place like `ProcessProposal` we are not in block execution but we don't want to fight for a read connection from RPC users.
> abci,txapp: on DB read pool use on consensus conn

- internal/engine/generate/plpgsql.go
- internal/engine/integration/procedure_test.go
- parse/analyze.go
- parse/parse.go
- parse/parse_test.go
This PR adds several tests, including:
- tests (and bug fixes) that ensure that all procedures that need a return have one. Without this check, users can hit unexpected plpgsql errors.
- tests for default ordering for aggregate and compound selects.
- tests for non-determinism checks with aggregates and group bys
> add missing return detection

- internal/engine/integration/procedure_test.go
- internal/sql/pg/db.go
- internal/sql/pg/sql.go
- parse/functions.go
This PR adds three functions from Postgres:
- encode/decode: https://www.postgresql.org/docs/current/functions-binarystring.html
- digest: https://www.postgresql.org/docs/current/pgcrypto.html#PGCRYPTO-GENERAL-HASHING-FUNCS-DIGEST
This was requested by the Truflation team, so they can generate DBIDs within a procedure: https://github.com/truflation/tsn/issues/280#issuecomment-2133458185
I also felt that these were pretty reasonable functions to want to have access to.
> added crypto functions, encode/decode

- cmd/kwil-cli/cmds/utils/parse.go
This fix `kwil-cli utils parse` output, so the output can be used for `kwil-cli database deploy`.  
We have a test kf file:
`$ echo "database test;" > /tmp/test.kf`
Before:
```
$ .build/kwil-cli utils parse /tmp/test.kf                                                                                           
{
"schema": {
"name": "test",
"owner": "",
"extensions": null,
"tables": null,
"actions": null,
"procedures": null,
"foreign_calls": null
}
}
$ .build/kwil-cli utils parse /tmp/test.kf > /tmp/test.json
$ .build/kwil-cli database deploy -p /tmp/test.json -t json
TxHash: 9a1f0200c2c7574f2e5f45c2546554ebb7a346d7b311ae0c3e1f4258f7953a3
$ .build/kwil-cli utils query-tx 9a1f0200c2c7574f2e5f45c2546554ebb7a346d7b311ae0c3e1f4258f7953a37
Transaction ID: …
```
> kwil-cli: fix `utils parse` output

- internal/engine/integration/procedure_test.go
- parse/analyze.go
- parse/functions.go
Added basic string manipulation functions. These are taken from the top-level SQL functions identified in Postgres: https://www.postgresql.org/docs/16/functions-string.html
This was requested by Truflation here: https://github.com/truflation/tsn/issues/284#issuecomment-2136359976
Documentation for supported functions can be found here: https://github.com/kwilteam/docs/pull/105/files#diff-aacab0e9719a83529316f1b99149bb81e25da9b918b53725d801890376d811a7
@outerlook does this cover what you need?
> added basic string manipulation functions

- cmd/kwil-cli/cmds/utils/parse.go
- parse/errors.go
- parse/types.go
This adds debug functionality for `kwil-cli utils parse`. It replaces https://github.com/kwilteam/kwil-db/pull/739
> added debug for cli parse

- core/types/schema.go
- internal/engine/execution/procedure.go
- internal/engine/execution/queries.go
- internal/engine/integration/procedure_test.go
- parse/functions.go
- parse/parse_test.go
This adds more tests for decimal and properly handles return types from `sum`, fixing a bug noted by Truflation https://github.com/truflation/tsn/pull/295.
It also fixes a variety of other small bugs, such as failure to catch runtime errors for calculations done on numeric array types, and not enforcing precision and scale on final results returned to the client.
> added tests for decimal

- cmd/kwil-cli/cmds/root.go
- cmd/kwil-cli/config/flags.go
This adds backwards compatibility for the `--kwil-provider` flag, which was changed to `--provider` in this release. Users will get a warning when they use this flag, however it will still work.
I think it is important to have a deprecation period for this, since both Fractal and Truflation have critical infra built around our CLI.
> added backwards compatibility for kwil-provider

- test/integration/kwild_test.go
Noticed that CLI integration tests were not being run, and that the flag was not set. Not sure when this happened.
> re-enable cli tests

- core/types/schema.go
- core/types/transactions/payload_schema.go
- internal/engine/execution/dataset.go
- internal/engine/execution/procedure.go
- internal/engine/generate/foreign_procedure.go
- internal/engine/integration/procedure_test.go
- parse/antlr.go
- parse/parse.go
This PR fixes several bugs, and adds tests for them.
Bugs:
- Data type metadata was not being copied properly https://github.com/truflation/tsn/issues/302
- Owner was not properly being enforced on external procedure calls
- Owner was not properly being enforced on foreign procedure calls. This was broken by a previous change that was made.
- Calling a non-view procedure outside of a blockchain tx that does not mutate state would not fail.
> fix: datatype pointer bug, access bugs

- cmd/kwild/main.go
- cmd/kwild/root/root.go
- cmd/kwild/server/build.go
- cmd/kwild/server/server.go
- internal/abci/abci.go
- internal/abci/cometbft/node.go
- internal/sql/pg/conn.go
- internal/sql/pg/db.go
- internal/sql/pg/repl.go
- internal/sql/pg/replmon.go
- internal/sql/pg/system.go
- internal/sql/pg/system_test.go
This addresses some UX issues around the DB connections.  When a connection dies unexpectedly (e.g. postgresql shutdown or connection broken), `kwild` would previously not find out until something on the consensus thread tried to use the connection.  It now breaks cleanly and immediately.  This makes it much more clear what failed and when.
Related to the cryptic errors seen with DB connection issues is a key timeout setting, `wal_sender_timeout`, that should be disabled.  Our `kwildb/postgres:16.2-1` image disable it, but the 16.1 image did not, and a system install does not by default.  `kwild` now checks to ensure that it is disabled.
Several other `postgres` settings that could affect determinism are also verified.  These are already the default settings for the most part.  We are now …
> pg,kwild: smoother handling of repl conn hangups, determinism guarantees 

- cmd/kwil-admin/cmds/snapshot/create.go
- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/server/build.go
- internal/abci/cometbft/node.go
PR includes the below fixes:
- Fix issues related to path of snapshot-file
- `kwil-admin snapshot create` used to create a snapshot file(empty) even in the error scenarios. It's misleading, removed that behavior in this PR
> Stop creating empty snapshots in the  error scenarioes.

- core/types/decimal/decimal.go
- core/types/decimal/decimal_test.go
I spotted a bug that occurs when we create a new decimal type where the exponent is greater than the precision. This causes issues when reading values from Postgres of type `decimal` where the value is greater than -1 and less than 1.
> fix: decimal bug from  exponent greater than precision

- cmd/kwil-cli/cmds/utils/parse.go
- internal/engine/integration/sql_test.go
- internal/sql/pg/query.go
- parse/actions.go
- parse/analyze.go
- parse/antlr.go
- parse/errors.go
- parse/functions.go
- parse/parse.go
- parse/parse_test.go
- parse/types.go
This fixes 3 parse errors that @KwilLuke found. Probably good for this to get backported, however it's not critical, as this simply fixes issues with errors output to the CLI and IDE.
The bugs are:
1. Parse error positions were being omitted if they occurred at the 0 line/column position. This was due to an `omitempty` tag that is no longer used anyways
2. Parse error types were not being included in the marshalled result.
3. Tables lacking primary keys were correctly identified as having errors, but the errors were not thrown in the parser, creating different error handling than other errors.
EDIT:
Also includes fixes for:
- `error` function not working in `SELECT CASE`
- The engine returning int literals as int32 instead of int64 (which all ints in kwil are assumed to be int64)
> fix parse bugs

- internal/txapp/txapp.go
While working through the Powerpod integration, I spotted a bug in our resolution code. If a resolution fails, it will halt consensus. This should not be the case, since resolutions are made to target databases, which can have arbitrary user-defined logic.
> fix error in resolve funcs

- cmd/kwild/config/default_config.toml
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/build.go
- internal/abci/abci.go
- internal/abci/cometbft/node.go
- internal/statesync/codes.go
- internal/statesync/snapshotter.go
- internal/statesync/statesync.go
- internal/statesync/store.go
This gets state sync working and fixes some tangential issues.
- add logging around state sync code, particularly with trusted rpc provider and snapshot retrieval and apply
- Fix the default and example config files using `snapshot_heights` instead of `recurring_height`
- Reduce the chunk size limit to < 16,000,000 bytes (previously was set at 16 MiB, not MB, plus lacked overhead space)
- With statesync restore error handling, return `ResponseApplySnapshotChunk_REJECT_SNAPSHOT` to cometbft as a fallback when the error is not typed.  `UNKNOWN` caused cometbft to fail rather than continue with another snapshot candidate.
With this and https://github.com/kwilteam/kwil-db/pull/812 we were able to get longhorn running and state sync on the sync node working.
> State sync fixes

- cmd/kwild/config/flags.go
- cmd/kwild/root/root.go
- cmd/kwild/root/root_test.go
PR fixes two issues I found regarding kwild flags.
1. `genesis-state` was not configurable via flags
2. extensions were not configurable via flags.
Adding genesis state was very straight forward. Extensions were tricky, because users should be able to specify any arbitrary extension name and key. To achieve this, I used the `--` delimiter from the [POSIX guidelines](<https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02>) (Guideline 10) to allow users to specify additional flag arguments for `kwild`. It verifies that these are correct flags for extensions:
```
kwild --autogen -- --my_ext.key=value --my_ext.key2 value2
```
> added genesis-state and extension flags

- .github/workflows/release.yaml
This update release workflow, to support kwil-db v0.8 mapping to kgw and kwil-js version
This should be backported to release-v0.8 branch
> ci: update release workflow support v0.8 version

- internal/txapp/txapp.go
The recent change made to log errors from resolutions logs as an error. This prints a full stack trace, which is not desirable. We should use warn instead.
Not critical, but should probably be backported for v0.8.2
> change log level for failed resolutions

- internal/voting/sql.go
@outerlook ran into an issue where Kwil indexes a column that we should not be indexing. This places an unnecessary constraint on the amount of data that can fit in an index.
> fix resolution body index

- cmd/kwil-cli/cmds/utils/parse.go
- internal/engine/execution/queries.go
- internal/engine/generate/foreign_procedure.go
- internal/engine/integration/procedure_test.go
- parse/contextual.go
This PR adds `@foreign_caller`, which gives information about what schema called another. If it is an outermost call, it will be an empty string (I tried to make it null, but due to Postgres not allowing unsettling of config parameters, and not allowing null config parameters, it does not appear possible).
This was requested by Truflation, as it is needed for their desired governance mechanisms for their schemas (https://github.com/truflation/tsn/issues/221). I can see how this would be useful information, so I felt it was appropriate to add.
This cannot be backported to v0.8.
> add foreign caller

- cmd/kwild/server/build.go
- internal/abci/abci.go
- internal/abci/utils.go
Profiling (`http/pprof`) under heavy transaction load revealed that there was major CPU utilization in `ProcessProposal` -> `validateProposalTransactions` at `ident.VerifyTransaction`.  This PR allows to skip that if the transaction (identified by hash) has already gone through this check in `CheckTx`, which would happen either via p2p gossip or rpc broadcast of the transaction.
WIP since there's a `txCache` map with a slightly different purpose that I may try to remove.
With this change, in a network with multiple validators that have to process another validator's block proposal, transaction throughput is much higher on account of much faster block proposal processing (can vanish almost 2 seconds).
> abci: skip repeated tx sig verification in proposal processing

- extensions/hooks/hooks.go
- internal/abci/abci.go
- internal/abci/abci_test.go
- internal/abci/interfaces.go
- internal/txapp/txapp.go
As per a discussion with the idOS team, we found an issue that could have been pretty elegantly solved by hooks that run arbitrary logic at genesis and at the end of a block. This is not the first time we have wanted these: in February, we wanted these hooks to build an Arweave integration. For migrations, I was also planning on a genesis hook. Given how stupid simple they are to implement, I decided to throw them together.
This also fixes a bug where the node identity is not being passed as part of the `*common.App` to other extensions.
> added genesis and commit hooks

- parse/errors.go
- parse/parse.go
Backport https://github.com/kwilteam/kwil-db/pull/838 to release-v0.8
> [v0.8.2] added look back for token errors

- internal/engine/generate/plpgsql.go
- internal/engine/integration/procedure_test.go
While working on a separate PR, I found a bug with unary expressions in procedures. The generated PL/pgSQL is missing a space, which generates invalid syntax.
I've fixed this and added a test case. I also re-read the PL/pgSQL generation code to check for other places where we might find this. I found two places where we _might_, but couldn't actually make negative cases for them. I added spaces to protect against them anyways.
> fix generated unary

- parse/ast.go
While reviewing something with @Yaiba , I realized that we had an unnecessary case in a switch statement. We checked for a UUID literal, but Kuneiform doesn't support UUID literals due to a deficiency in the ANTLR Go target making it impossible to parse.
> removed an unneeded uuid case

- cmd/kwild/config/config.go
In `kwild -h`, anything that was a Duration value returned the default as 0s. This is misleading, because the default is actually set elsewhere. This simply omits the default from being printed.
> fix: default time says 0s

- internal/engine/integration/procedure_test.go
- parse/analyze.go
- parse/antlr.go
- parse/ast.go
- parse/gen/kuneiform_parser.go
- parse/grammar/KuneiformParser.g4
This PR adds array assignment:
```typescript
$arr int[] := [1,2,3];
$arr[2] := 5;
// $arr == [1,5,3]
```
I saw Truflation had to use a really clunky function to handle this (search `set_array_element` at https://github.com/truflation/tsn/pull/322/files#diff-a02b595b78c18e341f0aceadec3f325c483d5f6d0abd3ec5da2b8e6ba13dbc3bR127), and realized that this was a glaring and easy to fix deficiency in Kuneiform.
> add array variable assignment

- internal/engine/execution/procedure.go
- internal/engine/execution/procedure_test.go
- internal/engine/generate/actions.go
As discussed here https://kwilteam.slack.com/archives/C0578NPEU21/p1719337560326199?thread_ts=1718905393.728919&cid=C0578NPEU21, the idOS team got tripped up expecting the engine to accept values that do not have dollarsigns. This is understandable, because virtually all other Kwil tooling makes the $ optional. This PR makes the dollarsign optional for the engine.
> make dollarsigns optional in engine

- internal/version/version.go
We're well into the v0.9 development cycle, so this PR makes `main` builds self-report as `v0.9.0-pre`.
This should always happen at the start of a new dev cycle, but it's extra helpful right now since users like to test `main` and `preview`.
> start of v0.9 devel cycle

- internal/engine/integration/sql_test.go
- parse/analyze.go
- parse/parse.go
- parse/parse_test.go
Resolves the bug found in https://github.com/kwilteam/kwil-db/pull/868 where `engine.Execute` can't use parameterized SQL.
> fix engine.Execute

- internal/engine/integration/sql_test.go
- parse/analyze.go
- parse/parse.go
- parse/parse_test.go
backports https://github.com/kwilteam/kwil-db/pull/871 to v0.8, to be included in v0.8.3
> [v0.8.3] fix engine.Execute

- internal/statesync/store.go
I ran into an issue where I stopped by node at just the right time where it was able to get bricked and become unrecoverable without manual intervention. While creating a snapshot, my node stopped, and was then unable to restart. It would crash on restart due to a nil pointer dereference. This PR fixes this.
> fix crash on invalid snapshot

- internal/statesync/store.go
backport https://github.com/kwilteam/kwil-db/pull/874
> [v0.8.3] fix crash on invalid snapshot

- internal/engine/execution/global.go
Fixes a bug where pgx is unable to infer types when using `engine.Execute`.
> Engine exec mode

- internal/engine/execution/global.go
- internal/engine/execution/procedure.go
- internal/engine/generate/plpgsql.go
- internal/engine/integration/sql_test.go
- parse/parse.go
This PR fixes two bugs:
1. Actions using in-line statements with type casts for ambiguous types would not generate SQL properly. This would only occur when performing an expression (such as a comparison). This is the main purpose of this PR.
2. Another very minor bug that caused a stack overflow when using the parse debugger tool was fixed. It was caused by having circular pointer references while removing error positions.
> fix in-line action error

- internal/engine/execution/global.go
- internal/engine/execution/procedure.go
- internal/engine/generate/plpgsql.go
- internal/engine/integration/sql_test.go
- parse/parse.go
backports https://github.com/kwilteam/kwil-db/pull/880
replaces https://github.com/kwilteam/kwil-db/pull/881
> [v0.8] fix: in-line type assertions not comparable 

- cmd/kwild/server/build.go
This fixes the bug where the kwild server build would not fail as intended if none of the trusted snapshot providers were valid.  We would see this:
```
2024-07-15T22:15:49.16Z warn    kwild   server/build.go:619     failed to get header from snap provider: post failed: Post "http://3.80.52.120:26657/": dial tcp 3.80.52.120:26657: connect: connection timed out
2024-07-15T22:15:49.162Z        info    kwild.abci      abci/abci.go:76 Preparing ABCI application at height 0, appHash
2024-07-15T22:15:49.188Z        info    kwild   server/build.go:323     closing signing store
2024-07-15T22:15:49.202Z        info    kwild   server/build.go:323     ending any active txApp transactions
2024-07-15T22:15:49.202Z        info    kwild   server/build.go:323     closing event store …
```
> kwild: failBuild was no-op if error was nil

- internal/engine/integration/procedure_test.go
- internal/sql/pg/db.go
- internal/sql/pg/db_live_test.go
- internal/sql/pg/sql.go
- parse/functions.go
Adds 2 functions:
- `parse_unix_timestamp(text, text) -> decimal(16,6)`: parses a datetime string to a UNIX timestamp. The first argument is the datetime string, the second is the formatting.
- `format_unix_timestamp(decimal(16,6), text) -> text`: formats a UNIX timestamp as a datetime string. The first argument is the UNIX timestamp, the second is the formatting for the result.
The formatting rules match Postgres's `to_timestamp` formatting: https://www.postgresql.org/docs/current/functions-formatting.html
This was requested by Truflation, and should be enough until we support a timestamp data type. It ended up being way easier to implement than I expected.
> add parse_unix_timestamp

- core/types/decimal/decimal.go
Fixes a weird aspect of the decimal `Cmp` method where it modifies one of the decimals.
> fix decimal cmp method

- core/client/client.go
- core/types/client/opts.go
This pr adds an option to skip checking chain info when create Client, this is useful to KGW to reduce the API calls to kwild.
> feature(core): option to skip checking chain info

- SECURITY.md
Updating the security policy now that v0.8 is the official latest release.
> chore: bump security policy for v0.8

- parse/parse.go
- parse/parse_test.go
@sapience noted a bug where a SQL statement that has a semicolon and whitespace after fails to parse if it is used with `enigne.Execute`. This is because `engine.Execute` directly uses the `parse.ParseSQL` function. This function allows SQL statements to optionally include a semicolon, and adds one if it is missing. It added an extra semicolon if the statement had whitespace.
The reason we had not run into this before is because all of the other parse functions (full schema, action, and procedure) remove the whitespace during tokenization. This error can _only_ occur if `engine.Execute` is called with whitespace trailing the semicolon.
> fix: extensions with sql whitespace fail

- internal/sql/pg/db_live_test.go
- internal/sql/pg/query.go
I tried to fix the uint256 type decoding issue, but unfortunately it appears to not really be possible. As noted [here](<https://www.postgresql.org/message-id/87fvoydtxx.fsf%40locaine.bese.it>), this is just part of Postgres.
Seems the only way to solve for this is with https://github.com/kwilteam/kwil-db/issues/800#issuecomment-2256723334
This PR removes one completely useless test, and changes query results to only read OIDs once per query, instead of once per row
> uint256 type decoding

- common/common.go
- common/context.go
- internal/abci/abci.go
- internal/engine/execution/queries.go
- internal/txapp/routes.go
- parse/contextual.go
- test/acceptance/test-data/contextual_vars.kf
- test/specifications/contextual_vars.go
I added an `@block_timestamp` variable. Both Truflation and idOS requested this in the last 2 weeks.
We should make sure to note that this can be spoofed, since it is just based off of block time. A less-spoofable version could be added using cometbft's vote extensions, but that is something we can add at a later date.
> added @block_timestamp

- internal/engine/integration/procedure_test.go
- parse/functions.go
The new `generate_dbid` function generates a syntax error if it is used with assignment (`:=`). I fixed this and added a test for it.
> fix: generate_dbid() generates syntax error

- cmd/kwil-cli/cmds/utils/test.go
- testing/testing.go
While using the testing tool, I noticed two weird messages.
One of them was with the CLI. It had a flag description that I had copied over from snapshotting, and thus had an irrelevant description. The second of them was an error message for failed tests that could've been more helpful and accurate.
> added better messages for testing

- cmd/kwil-admin/cmds/common/rpc.go
- core/adminclient/client.go
- core/adminclient/opts.go
- core/rpc/client/jsonrpc.go
- internal/services/jsonrpc/server.go
```
core/{rpc,adminclient},kwil-admin: set/use optional admin service password
This updates the admin RPC client with the ability to set the admin
RPC password, which was introduced when the server was converted to
JSON-RPC.
This also updates kwil-admin with a "--pass" flag to specify it.
With security implications in mind, an optional file at
~/.kwil-admin/rpc-admin-pass will be loaded if the --pass flag is
omitted and the file exists.
Finally, this fixes a nil ptr bug in the JSON-RPC admin server.
NOTE: if using curl, use the "-u" flag with "user:pass", where "pass"
is the intended password.  The "user" part is ignored but required
for HTTP Basic authentication to work properly.
```
As a reminder, back when we only had gRPC for the admin server, there were limited solutions for …
> admin: set/use optional admin service password

- cmd/kwil-admin/cmds/setup/peer.go
Removes an incorrectly documented flag `--peers`, as noted [here](<https://github.com/truflation/tsn/issues/393#issuecomment-2283364060>)
> removed unnecessary peer flag

- common/sql/sql.go
- common/sql/statistics.go
- core/types/decimal/decimal.go
- core/types/uint256.go
- go.mod
- go.sum
- internal/sql/pg/conn.go
- internal/sql/pg/db_live_test.go
- internal/sql/pg/query.go
- internal/sql/pg/repl_test.go
- internal/sql/pg/stats.go
- internal/sql/pg/stats_test.go
- internal/sql/pg/system.go
- internal/sql/pg/tx.go
- internal/sql/pg/types.go
- test/go.mod
- test/go.sum
This at least partially resolves #800, and provides some foundational components for table statistics collection (https://github.com/kwilteam/kwil-db/issues/410).  I have more work done on stats in both engine and pg for incremental updates, but the pieces in this PR were substantial, so I pulled them out for easier review.
This adds functionality to the `pg` package:
- Table inspection: the `ColumnInfo` function and the `ColInfo` and `ColType` types provide a way to inspect any postgresql table without knowledge of the scheme. The `(*ColInfo).ScanVal` method provides an instance of a suitable type into which a column expression may be scanned in one of the new advanced query methods described below.
- Advanced query execution:
* the `sql.QueryScanner` interface is the advanced version of …
> pg: advanced query feats, table inspection, and stats

- core/types/uint256.go
- core/types/uint256_test.go
- core/types/uuid.go
- core/types/uuid_test.go
This is some more small fixes coming out of my statistics work branch.  This fixes and tests round trip json marshaling for both `types.Uint256` and `types.UUID`, and adds binary marshalling for `Uint256`.
The standard libarary's `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` interfaces have special significance for several packages in the standard library, most notably `encoding/gob`, which is a simple and convenient way to encode Go structs containing interfaces and custom types.
> types: uint256 and uuid marshaling fixes

- parse/planner/logical/mappings.go
- parse/planner/logical/nodes.go
- parse/planner/logical/planner.go
This PR simplifies comparisons in logical plans by limiting the number of operators. I felt this change was good b/c of how I am managing them within procedures.
> simplify expressions in the planner

- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/build.go
- internal/services/jsonrpc/server.go
This adds a configurable request size limit to kwild.
In toml: `app.rpc_req_limit`
With cli flag: `--app.rpc-req-limit`
The default is somewhat arbitrarily 4,200,000 bytes.
If the network's genesis config sets max transaction size larger than this limit, kwild warns on startup.
> kwild,jsonrpc: add app.rpc-req-limit / cfg.AppCfg.RPCMaxReqSize

- parse/antlr.go
- parse/parse_test.go
This PR fixes a bug I found where string literals that end in an escaped single quote (e.g. `'hello world \''`) incorrectly remove the escaped quote.
> fix: parse bug with string literals

- cmd/kwil-admin/cmds/migration/approve.go
- cmd/kwil-admin/cmds/migration/cmd.go
- cmd/kwil-admin/cmds/migration/genesis.go
- cmd/kwil-admin/cmds/migration/list.go
- cmd/kwil-admin/cmds/migration/propose.go
- cmd/kwil-admin/cmds/migration/status.go
- cmd/kwil-admin/cmds/snapshot/create.go
- core/types/types.go
- internal/migrations/migrator.go
- internal/services/jsonrpc/adminsvc/service.go
- internal/services/jsonrpc/usersvc/service.go
- test/specifications/migration.go
This PR does a few minor things pertaining to recent migrations code in various packages:
- In `core/types/MigrationMetadata` change the `GenesisConfig` and `SnapshotMetadata` fields from `[]byte` to `json.RawMessage`. This is the preferred type when delaying the unmarshal of raw JSON, which is exactly the case as we unmarshal these into internal types.  This avoids the RPC service/client from having to needlessly round trip the content, which is already text (JSON), to base64 and back.  This is very similar to changing the field to a `string`.  There are no visible changes unless using `curl` to see the raw response.
- In each of the `cmd/kwil-admin/cmds/...`, cleanup various typo, use the `cmd.Context()`, set arg counts, docs tweaks, etc.
- Rename `internal/migrations.ChangesetMetdata` …
> types,migrations,admin,rpc: cleanup and migrations type fix

- extensions/consensus/consensus.go
- internal/abci/abci.go
- internal/abci/utils.go
Updates to the recently added `MaxVotesPerTx` consensus parameter (kwil-specific, not cometbft) was omitted from the ABCI DB.  This updates ABCI and the param merge helper function.
> abci,consensus: include MaxVotesPerTx in abci db and param updates

- internal/migrations/changesets.go
- internal/migrations/changesets_test.go
- internal/migrations/migrator.go
- internal/sql/pg/repl_changeset.go
- internal/sql/pg/repl_changeset_test.go
This PR has two closely related commits:
1. https://github.com/kwilteam/kwil-db/pull/942/commits/b1f9c903f69f9f92628ad705131ebed51ebd097d In changesets, the `ChangesetElentry` for an UPDATE includes both old and new values.  All of the old values are required, to be used with a fully-specified `WHERE` clause.  However, only the changed *new* values need to be included in the `SET` clause.  This commit deduplicates this unchanged data from the changesets.  This can drastically reduce the size of the serialized changesets (imagine only modifying an integer column and other large bytea/text columns unchanged), which must be stored and trasmitted cross-chain and then recorded permanently in governance transactions on the new chain.   The second reason it is helpful to flag these values as …
> pg: elide unchanged tup vals in UPDATE changeset

- cmd/common/display/format.go
- cmd/common/display/format_test.go
- cmd/common/display/message_test.go
- test/driver/cli_driver.go
This fixes an error that has been logged on CI for a while, but not actually breaking the test outcomes.
Unmarshalling into a generic struct fails if the typed result field is meant to be unset when an error field is set.
`{"level":"error","ts":1725487903.0891304,"caller":"driver/cli_driver.go:436","msg":"bad cmd output","error":"json: cannot unmarshal string into Go struct field cliResponse[github.com/kwilteam/kwil-db/test/driver.respTxQuery].result of type driver.respTxQuery","output":"{\n  \"result\": \"\",\n  \"error\": \"error querying transaction: not found\\njsonrpc.Error: code = -202, message = transaction not found, data = null\\nerr code = -202, msg = transaction not found\"\n}\n","goversion":"go1.23.0","stacktrace":"github.com/kwilteam/kwil-db/test/driver.mustRun[...] ...}`
A …
> test: fix generic result unmarshalling

- common/common.go
- common/context.go
- extensions/consensus/payloads.go
- extensions/precompiles/actions.go
- extensions/precompiles/adhoc.go
- internal/abci/abci.go
- internal/abci/abci_test.go
- internal/abci/interfaces.go
- internal/engine/execution/dataset.go
- internal/engine/execution/execution_test.go
- internal/engine/execution/global.go
- internal/engine/execution/procedure.go
- internal/engine/execution/queries.go
- internal/engine/integration/deployment_test.go
- internal/engine/integration/execution_test.go
- internal/engine/integration/procedure_test.go
- internal/engine/integration/schema_test.go
- internal/engine/integration/sql_test.go
- internal/extensions/extensions_test.go
- internal/extensions/remote_extensions.go
- internal/services/jsonrpc/usersvc/service.go
- internal/txapp/routes.go
- internal/txapp/routes_test.go
- internal/txapp/txapp.go
- test/nodes/fork/gremlin.go
- testing/testing.go
Ok this was the last major change I wanted to make before we have another release.
This change removes/refactors some unnecessary structs in `common`, and unifies them. In particular, we had essentially two structs that do the same thing, and we often switch between them. The reason I felt this change was necessary is because there are currently some very awkward patterns used in extensions (resolutions in particular) that are the result of not properly duplicating fields/information in these structs.
Therefore, this is a breaking change, however it is trivially easy to port over old extensions, and extensions already received a breaking interface change in this release.
> unified common structs used throughout codebase

- internal/abci/abci.go
This is already on `preview` to resolve a consensus failure resulting in a second block with a misbehavior report for a certain validator.
```
Do not have consensus failure if a misbehavior is reported to ABCI for a validator that has already been forgotten (removed).
```
> abci: handle misbehavior more gracefully

- go.mod
- parse/go.mod
- test/go.mod
We aren't branching or removing `replace` statements for the `v0.9.0-beta` release, but to assist custom builds, this updates the `core` entries in each go.mod with a *pseudo-version*.  This can also be done manually in the consuming project, but this provides the hint to get a non-broken build.
After this is merged, one more PR with updates for `parse` should follow.
As a reminder, with the `replace` statements remaining in the go.mod, files: (1) it is an error if trying to `go install` or `go run` one of the `cmd/...` apps, and (2) any `replace` statements get **ignored** if you are importing one of our packages like `core` or the main  module to build a custom app, like `tsn`.  Hence, `replace` statements will be removed for final/candidate release.
> deps (1/2): update go.mod core deps, next is parse

- cmd/kwild/server/build.go
- internal/abci/abci.go
- internal/statesync/snapshot.go
- internal/statesync/statesync.go
As discussed earlier, we hit a sync issue with TSN testnet due to Comet trying to verify too many block headers. Since our snapshot providers are trusted anyways, this isn't necessary. I added the ability to query ABCI for the latest snapshot from a node, so that we can avoid this.
This is untested, but I just wanted to get something for it because I need to get going and I didn't want to lose my train of thought on it. There is a TODO in there asking about why we don't return errors in a certain part of ABCI (CC @charithabandi you might be able to answer this for me)
> added latest snapshot height querying

- internal/engine/generate/generate.go
- internal/engine/generate/procedure.go
- internal/engine/generate/procedure_test.go
- internal/engine/generate/utils.go
This adds a delimiter `$kwil_reserved_delim$`, and checks that users aren't trying to maliciously use it in procedure or table creation.
We should not backport this to the TSN fix, since it is a breaking change with how snapshots are created.
> check for invalid delimiter

- build/package/docker/kwild.debug.dockerfile
- build/package/docker/kwild.dockerfile
- deployments/compose/kwil/docker-compose.yml
- test/acceptance/docker-compose-dev.yml
- test/acceptance/docker-compose.yml
- test/integration/docker-compose-dev.yml
- test/integration/docker-compose-migration.yml.template
- test/integration/docker-compose.yml.template
This uses the new health check endpoints with CI to get a more meaningful idea of node container readiness.
This is an effort to resolve #967
> CI: use app health check endpoint

- cmd/kwil-admin/cmds/setup/init.go
- cmd/kwil-cli/cmds/database/batch.go
- cmd/kwil-cli/cmds/database/call.go
- cmd/kwil-cli/cmds/database/deploy.go
- cmd/kwil-cli/cmds/database/execute.go
- cmd/kwil-cli/cmds/database/flags.go
- cmd/kwil-cli/cmds/database/query.go
- cmd/kwil-cli/cmds/database/read_schema.go
- cmd/kwil-cli/config/flags.go
- test/driver/cli_driver.go
While going through the docs, I noticed that we liberally use `--action` everywhere with `kwil-cli`. This isn't quite accurate, since anywhere we specify `--action` we can also use a procedure. Therefore, I deprecated `--action`, and added a `--target` flag.
> deprecates --action, should now be passed as positional argument

- cmd/kwil-admin/cmds/setup/init.go
- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- common/common.go
- common/config/config.go
- common/context.go
While going through the docs, some commands or documentation that I don't like or are incorrect I am making minor changes to. Still WIP.
I've added a few new flags for configs that were set-able via `config.toml`, but not with flags.
- `--chain.p2p.dial-timeout` flag
- `--chain.p2p.handshake-timeout` flag
I've also fixed the `--log.consensus-level` flag, which previously used an underscore.
I renamed the `app.rpc-req-limit` config because I felt that it was terribly confusing. The name makes me think that there is some configurable limit to the requests that the RPC can process, but in reality, it is a max request size config. I renamed it to `app.max-req-size`, and have deprecated the old one.
> minor documentation updates, config name changes

- cmd/common.go
- cmd/kwil-admin/cmds/root.go
- cmd/kwil-admin/cmds/setup/init.go
- cmd/kwil-admin/cmds/snapshot/create.go
- cmd/kwil-admin/cmds/whitelist/add.go
- cmd/kwil-admin/cmds/whitelist/cmd.go
- cmd/kwil-admin/cmds/whitelist/list.go
- cmd/kwil-admin/cmds/whitelist/remove.go
- cmd/kwild/config/folders.go
- cmd/kwild/server/build.go
- cmd/kwild/server/cometbft.go
- cmd/kwild/server/cometbft_test.go
- cmd/kwild/server/utils.go
- common/config/config.go
- internal/statesync/snapshotter.go
- internal/statesync/snapshotter_test.go
- internal/statesync/store.go
- test/driver/operator/cli_driver.go
- test/integration/helper.go
- test/integration/kwild_test.go
- Remove max-row-size config and update snapshot creation process to handle any row data sizes
- unexpose(removed) trust options in the statesync config as they are not user configurable. 
- Rename `kwil-admin peers` to `kwil-admin whitelist`
> Cleanup snapshots, statesync and whitelist peers

- internal/migrations/changeset_listener.go
- internal/migrations/changesets.go
- internal/migrations/changesets_test.go
- internal/migrations/migrator.go
- internal/migrations/sql.go
- internal/txapp/interfaces.go
- internal/txapp/routes.go
- internal/voting/sql.go
- internal/voting/vote_test.go
- internal/voting/voting.go
- test/specifications/migration.go
This PR optimizes the migration process on the new network, by not submitting the resolutions with empty changesets thereby reducing the number of resolutions to be processed and voted on the new network.
Also fixes any issues concerning if the changeset migration resolution can fit within a block. All the changeset chunks are readjusted to the blocksize/3 on the new network.
> Optimize the migration process on the new network

- test/go.mod
- test/utils/container.go
@Yaiba had the idea that perhaps the integration test's network needs to be different, in particular, not overlapping with the subnet used by the github actions environment
> ci: non-overlapping net for gh actions

- internal/txapp/interfaces.go
- internal/txapp/txapp.go
backport: https://github.com/kwilteam/kwil-db/commit/b4da094c333987207a75832a5fd5b181bb307943
> abci: Create snapshots if snapshots are enabled and none exists

- cmd/kwil-admin/cmds/setup/init.go
- cmd/kwil-admin/cmds/setup/testnet.go
- common/chain/chaincfg.go
The default validator join expiry of 1 day turned out to be too short in practice.  This increases it to 1 week (100800 blocks of 6 second blocks by default).
> config: 1 week join expiry default

- cmd/common.go
- cmd/kwild/config/config.go
- cmd/kwild/config/config_test.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/build.go
- cmd/kwild/server/cometbft.go
- common/config/config.go
- go.mod
- internal/services/jsonrpc/server.go
I want to play with prometheus a bit before saying this is right, but it addresses exposing cometbft's metrics as in https://github.com/kwilteam/kwil-db/issues/995#issuecomment-2369289713
Prometheus server + Grafana can talk to this and see cometbft's metrics, so I think this is properly exposing CometBFT's metrics endpoint.
Metrics: https://docs.cometbft.com/v0.38/core/metrics
prometheus config
```yml
global:
scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
alertmanagers:
- static_configs:
- targets:
rule_files:
scrape_configs:
- job_name: "prometheus"
scrape_interval: 5s
static_configs:
- targets: ['localhost:26660']
```
> add prometheus metrics server and config

- cmd/kwil-admin/cmds/common/rpc.go
- cmd/kwil-admin/cmds/setup/genesis-hash.go
- cmd/kwil-admin/cmds/setup/reset-state.go
- cmd/kwil-admin/cmds/setup/reset.go
Fixes a bug where `kwil-admin setup reset` was not properly reading in Postgres configs from the `config.toml` in the root directory.
> fix: kwil-admin setup reset does not use custom pg config

- cmd/kwild/server/server.go
- internal/version/version.go
Resolves https://github.com/kwilteam/kwil-db/issues/1016
Although we print the version string to stdout, we didn't write it to logger.
I think we should still write to std out important info before we start the logger, but this will now write to the logger (i.e. their log file and not lost to stdout):
```
2024-09-25T13:41:57.435-05:00	info	kwild	version 0.9.0-pre+b35de9da4.dirty commit b35de9da4
```
in context:
```
$  ./kwild -r ~/.kwild-junk3
kwild version 0.9.0-pre+b35de9da4.dirty (Go version go1.23.1)
Root directory "/home/jon/.kwild-junk3"
Private key path: /home/jon/.kwild-junk3/private_key
WARNING: app.rpc_req_limit is deprecated and will be removed in Kwil v0.10. use app.rpc_max_req_size instead
Started with 0 configured hard fork heights:
- halt: <nil> (disabled) …
```
> kwild: write version to log file too

- cmd/kwil-admin/cmds/setup/genesis.go
Fixes a conflicting flag name in the `genesis` command. For some reason, Cobra did not complain, but instead silently failed to add the flag.
> fix output

- Taskfile.yml
- cmd/kwil-admin/nodecfg/generate.go
- test/acceptance/helper.go
- test/acceptance/kwild_test.go
- test/integration/helper.go
This pr add support to config `private_rpc`,  so that following cmds work:
- `KACT_PRIVATE_RPC=true task dev:up:nb`
- `KIT_PRIVATE_RPC=true task dev:testnet:up:nb`
This helps to test KGW.
Merge note: squash
> test: allow config private rpc

- common/sql/sql.go
- internal/abci/abci.go
- internal/sql/pg/db.go
This resolves a possible hang in `FinalizeBlock` if the DB shuts down / dies while waiting for the completion of the notice stream at `wg.Wait()`.  When the `pg.DB` instance closes up in response to the replication connection terminating, we also make sure to close the subscriber channels to unblock the receivers.  To ensure the receivers handle this as an error rather than assuming all notices have been received successfully, an empty string is first sent on the channel.  Since all notice messages have a special prefix (`pgtx:`), this is easily recognized as an exception.
> pg,abci: unblock notice subscribers on DB shutdown

- SECURITY.md
- cmd/kwil-admin/cmds/common/rpc.go
- cmd/kwil-admin/nodecfg/toml.go
- cmd/kwild/config/config.go
- cmd/kwild/config/config_test.go
- cmd/kwild/config/default_config.toml
- cmd/kwild/config/flags.go
- cmd/kwild/config/test_data/config.toml
- cmd/kwild/server/cometbft.go
- cmd/kwild/server/server.go
- common/config/config.go
- internal/abci/cometbft/node.go
Resolves https://github.com/kwilteam/kwil-db/issues/999 (except for docs repo, which I'll address too)
> config,cmds: prefix admin- to tls-{cert,key}-file settings

- cmd/kwild/server/build.go
- internal/sql/pg/db.go
- internal/sql/pg/sql.go
resolves https://github.com/kwilteam/kwil-db/issues/1025
> pg: ensure all tables have full replica identity

- cmd/kwil-admin/cmds/migration/genesis.go
- cmd/kwil-admin/cmds/migration/list.go
- cmd/kwil-admin/cmds/migration/propose.go
- cmd/kwil-admin/cmds/setup/genesis.go
- cmd/kwild/server/migration.go
- common/chain/chaincfg.go
- core/types/types.go
- internal/migrations/migrations.go
- internal/migrations/migrator.go
- internal/migrations/sql.go
- internal/services/jsonrpc/usersvc/service.go
- internal/statesync/snapshot.go
- internal/version/version.go
- test/driver/operator/cli_driver.go
- test/driver/operator/client_driver.go
- test/integration/kwild_test.go
- test/specifications/dsl.go
- test/specifications/migration.go
This PR simplifies migration structs. There are three key changes:
1. It removes `chain-id` from the migration proposals, since they are effectively a suggestion anyways.
2. It simplifies the struct that is passed back from the client when querying for migrations. It previously used to return serialized genesis.json, but now returns a much slimmed down struct that only contains necessary info.
3. It adds kwild's minor version to the migration metadata when querying a node. This is because we still send the snapshot metadata serialized, and thus need to maintain compatibility between versions. I thought about moving snapshot metadata into `core/types`, but didn't to keep it simple.
> Simplify Migration Structs

- .github/workflows/ci.yaml
- Taskfile.yml
- build/package/docker/postgres.dockerfile
- deployments/compose/kwil/docker-compose.yml
- deployments/compose/kwil/init.sql
- deployments/compose/postgres/docker-compose.yml
- deployments/compose/postgres/init.sql
- test/acceptance/docker-compose-dev.yml
- test/acceptance/docker-compose.yml
- test/acceptance/pginit.sql
- test/integration/docker-compose-dev.yml
- test/integration/docker-compose-migration.yml.template
- test/integration/docker-compose.yml.template
- test/integration/helper.go
- test/integration/pginit.sql
- testing/testing.go
This updates our customized `postgres` Docker image in `build/package/docker/postgres.dockerfile` to extend the official `postgres:16.4` image, bumped from 16.2.  I have been using 16.4 since it's release it's release about 2 months ago, and I think it's a good idea to update our official image before 0.9 release.
This PR also starts using *our* postgres image in all of our tests.  It was used for the pg-enabled unit tests, but not in acceptance or integration tests.  We should be testing our image more consistently.  What this means is not of the special startup flags or the injected pginit.sql script need to be part of the docker compose files since they are already part of our extended postgres image.
NOTE: I have already pushed `kwildb/postgres:16.4-1` to Docker Hub, but I have not …
> update our pg docker image to 16.4, and use in test

- cmd/kwild/server/build.go
- cmd/kwild/server/cometbft.go
- internal/abci/abci.go
This is a kinda dopey way to avoid making a snapshot at `InitialHeight`, which may or may not be 1, where that block's timestamp is the genesis time set in genesis.json that is often quite a bit older than the next block.  This results in an expired header error on statesync observed:
`"msg":"Can't verify","module":"statesync","module":"light","err":"verify from #1 to #2 failed: old header has expired at 2024-09-20 19:15:21.961570453 +0000 UTC (now: 2024-10-01 16:17:07.80072020`
I wasn't eager to store block time in our meta store to do this the proper way, and we can't simply do this on block 2 since InitialHeight is not always 1.  Did I miss a much simpler way in my pre-lunch fog?  Should I have just injected the initial height at Abci construction?
> abci: workaround for snapshots at initial height having old time

- cmd/kwild/server/build.go
- cmd/kwild/server/cometbft.go
- common/chain/chaincfg.go
- extensions/consensus/consensus.go
- internal/abci/cometbft/genesis.go
- internal/abci/utils.go
- test/nodes/fork/gremlin.go
Consider this diff as **for discussion**.
The application "protocol version" is set in genesis as `ConsensusParams.Version.App`.  This is a cometbft consensus parameter, and we have always given it 0.
Major Kwil versions effectively change this version, and although we may keep it the same, the result of running incompatible Kwil versions on the same network is generally a hard to debug app hash mismatch as a result of any logic that affects its computation such as tx execution changes, the commit ID computed in pg logical replication, etc.
By updating the app version, we instead fail fast at startup when attempting to perform blocksync with a peer running an incompatible app version:
`{"level":"error","ts":1727467648.7178495,"logger":"kwild.cometbft","msg":"Error in …
> chain: bump appVersion to 1

- UPGRADING.md
- docs/release-notes/release-v0.9.md
- docs/release-v0.9.md
Rendered markdown [here](https://github.com/jchappelow/kwil-db/blob/relnotes-0.9/docs/release-v0.9.md).
We decided it is good to have these in a `docs/release-notes` folder, so that's where I put it.
> docs: add release notes for v0.9

- core/rpc/client/admin/admin.go
- core/rpc/client/admin/jsonrpc/client.go
- core/rpc/json/admin/commands.go
- core/rpc/json/admin/methods.go
- core/types/transactions/payloads.go
- internal/services/jsonrpc/adminsvc/service.go
- internal/txapp/interfaces.go
- internal/txapp/routes.go
- test/driver/operator/client_driver.go
The delete resolution route was not registered with the tx app's router, nor was it tested, so this removes the client methods and the RPC service handler until we've properly tested the tx route (and motivated it).
> rpc,txapp,voting: disable delete resolution route

- internal/services/jsonrpc/methods.go
- internal/services/jsonrpc/server.go
Will add an OPTIONS unit test, but please see if this works with browser clients.
> rpc: fix cors because of blocked OPTIONS

- test/utils/container.go
Since we cannot set Docker's `default-address-pools` in daemon.json on Github Actions like we did our our old self-hosted running, this PR attempts to pick random /20 networks in 10.A.B.0/20 (there are 4096 subnets each with 4096 addresses) rather than use "10.9.0.0/16", which can cause trouble if the network isn't taken down fast enough or if a test fails and decides not to clean up the network, which can break subsequent tests without different networks.
> test: randomized non-overlapping networks on 10.A.B.0/20

- internal/services/jsonrpc/methods.go
- internal/services/jsonrpc/server.go
- internal/services/jsonrpc/server_test.go
- internal/version/version.go
This adds unit tests to the `jsonrpc` server to ensure the http mux and middleware stack handle CORS correctly, accepting `OPTIONS` requests if the server has cors enabled.  The test also cover some basic json-rpc method handling behavior.
A second commit updates `internal/version/version.go` to report `v0.9.2-pre`.  We have tagged `v0.9.1`, and using the branch on a commit past that tag would ideally report a build from a "prerelease" revision of the next sequential version, which would be `v0.9.2`.  I normally don't bother to bump batch version ahead of time like this, but I think it makes sense.
> rpc: test cors, and respect option on rest endpoints

- cmd/kwil-admin/cmds/setup/init.go
- cmd/kwil-admin/nodecfg/generate.go
- core/utils/files.go
- internal/statesync/snapshotter_test.go
- test/specifications/migration.go
Requires and based on https://github.com/kwilteam/kwil-db/pull/1059
Resolves https://github.com/kwilteam/kwil-db/issues/1057
This change alters how `setup init` handles the `--app.private_key_path` flag.
Recently it was modified to ignore the flag entirely, with the apparent intent of ensuring the generated `config.toml` in the initialized root directory would always be `private_key_path = "private_key"` with the actual private key always being written into the root directory. This behavior is good, however, when the flag is set it is desirable to import the private key file pointed to by this flag, which is what this change does.
This new behavior streamlines the production deployment guide where the workflow for the genesis validator set involves preparing the private keys so that then …
> admin: use specified private key with setup init

- cmd/kwild/config/config.go
- cmd/kwild/config/flags.go
- cmd/kwild/server/build.go
From @outerlook via Slack:
> Frontend team from time to time still crashes the server batching requests. Is that option to reduce requests concurrency available?
https://github.com/kwilteam/kwil-db/blob/cb0f6f6c19644f9ec405078b54c615eb4c6e8d35/cmd/kwild/server/build.go#L429
how much effort would it take to make this 24 configurable? Also it's expected that with this lower value, a queue system will kick in to manage requests, or would them fail?
This PR adds a `app.db-max-connections` flag which specifies the maximum number of connections the engine will hold to Postgres. The default is still 24, but it is now configurable. The minimum is 2, and kwild will fail quickly if the user configures 1.
I did some local testing to ensure that this applies backpressure properly, and can confirm it …
> Preview max db conns

- cmd/common.go
- cmd/kwild/config/flags.go
- cmd/kwild/server/build.go
- common/config/config.go
Adds https://github.com/kwilteam/kwil-db/pull/1064 to v0.9
> added max db connections config

- .github/workflows/kgw-test-reuse.yaml
- core/client/client.go
- core/rpc/client/error.go
- core/rpc/client/jsonrpc.go
- core/types/client/opts.go
- a11fe98ce58ccf0ca0bfb61d6cab4cf7cc570d6e supports a new client option `SkipHealthcheck`. If this option is set, errors from calling `user.health` API will be ignored, and fall back to `user.chain_info` to get ChainID.
- a30c0499fcb6d02728b0010e42b3e167db1a300a fix CI to build KGW together with kwil-db in workspace
Note: I push to kwilteam/kwil-db repo so I can manually trigger CI.
kwilteam/kgw#96 depends on this
> feat(core): support skip health check option

- internal/sql/pg/repl.go
- internal/sql/pg/repl_msgs.go
Fixes `Error: decodeWALData failed: parse logical replication message: replication message not supported` preceded by:
```
2024-10-22T10:03:48.805-05:00	error	kwild.cometbft	CONSENSUS FAILURE!!!	{"module": "consensus", "err": "failed to apply block; error failed to precommit transaction: replication stream interrupted", "stack": "goroutine 490 [running]:\nruntime/debug.Stack()\n\t/home/jon/go123/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/home/jon/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:801 +0x46\npanic({0x15b29c0?, 0xc0089e7720?})\n\t/home/jon/go123/src/runtime/panic.go:785 +0x132\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc0002df188, …
```
> pg: recognize streaming prepared tx msg

- internal/engine/generate/actions_test.go
- internal/engine/generate/plpgsql.go
This fixes a bug in `engine/generate.(*sqlGenerator).VisitExpressionVariable` where an explicit typecast would be lost where:
1. there are multiple occurrences of an ordered parameter in an action body
2. any of the occurrences other than the first have an explicit typecast
> engine/generate: fix repeated numbered arg typecast

- build/package/docker/postgres.dockerfile
- common/sql/sql.go
- common/sql/sql_test.go
- internal/abci/abci.go
- internal/sql/pg/query.go
- internal/sql/pg/tx.go
There are certain errors from the database that indicate failures of the DB backend itself, such as out of memory/disk or corruption etc.
Unfortunately, these were not halting the node, only resulting in failed blockchain transactions, thus non-determinism since it would still compute an apphash (likely incorrect) and commit the block:
```
2024-11-14T15:25:16.331Z	warn	kwild.pg	pg/conn.go:137	ERROR [53200]: out of shared memory
2024-11-14T15:25:16.332Z	warn	kwild.abci	abci/abci.go:371	failed to execute transaction	{"error": "ERROR: out of shared memory (SQLSTATE 53200)\ninternal database error"}
2024-11-14T15:25:16.336Z	warn	kwild.abci	abci/abci.go:371	failed to execute transaction	{"error": "ERROR: out of shared memory (SQLSTATE 53200)\ninternal database error"}
2024-11-14T15:25:16.34Z …
```
> sql,pg: catch db backend failure

- build/package/docker/postgres.dockerfile
- common/sql/sql.go
- common/sql/sql_test.go
- internal/abci/abci.go
- internal/engine/generate/actions_test.go
- internal/sql/pg/query.go
- internal/sql/pg/repl_test.go
- internal/sql/pg/tx.go
Port of https://github.com/kwilteam/kwil-db/pull/1079 to `preview`
> [preview] sql,pg: catch db backend failure

- build/package/docker/postgres.dockerfile
- common/sql/sql.go
- common/sql/sql_test.go
- internal/abci/abci.go
- internal/sql/pg/query.go
- internal/sql/pg/tx.go
Backport of https://github.com/kwilteam/kwil-db/pull/1079 to `release-v0.8`
> [v0.8] sql,pg: catch db backend failure

- cmd/kwild/server/build.go
This fixes a bug where a deprecated field was not being set properly, causing it to be a breaking change within the deprecation period.
> fix: deprecated extension config map not set properly

- common/context.go
- internal/services/jsonrpc/usersvc/service.go
https://github.com/kwilteam/kwil-db/pull/1094 for `release-v0.9`
> [v0.9] jsonrpc/usersvc: use best block height/time in view call

- common/context.go
- internal/services/jsonrpc/usersvc/service.go
Alternative to https://github.com/kwilteam/kwil-db/pull/1088
Resolves https://github.com/kwilteam/kwil-db/issues/1084
```
action get_post($id) public view {
SELECT *, @block_timestamp as stamp, @height as height
FROM posts
WHERE id = $id;
}
```
```
$  kwil-cli database call -i xc4503ccf15daada96e36cbbacf641f48ebc6226e28906c8757866b91 -a get_post 'id:3'
| content | height | id |   stamp    | title  | user_id |
+---------+--------+----+------------+--------+---------+
| hihi    |    842 |  3 | 1732569623 | title2 |       1 |
$  kwil-cli database call -i xc4503ccf15daada96e36cbbacf641f48ebc6226e28906c8757866b91 -a get_post 'id:3'
| content | height | id |   stamp    | title  | user_id |
+---------+--------+----+------------+--------+---------+
| hihi    |    843 |  3 | 1732569630 | title2 …
```
> jsonrpc/usersvc: use best block height/time in view call

- cmd/kwil-cli/cmds/database/batch.go
- cmd/kwil-cli/cmds/database/call.go
- cmd/kwil-cli/cmds/database/execute.go
- cmd/kwil-cli/cmds/database/flags.go
Adds https://github.com/kwilteam/kwil-db/pull/1100 to release
> [v0.9] add all-scalar flag

- cmd/kwil-cli/csv/csv.go
- cmd/kwil-cli/csv/csv_test.go
- cmd/kwil-cli/csv/json.csv
Backport of https://github.com/kwilteam/kwil-db/pull/1099 to `release-v0.9`
> [v0.9] fix csv parsing issue

- app/shared/display/message.go
- cmd/kwil-cli/cmds/utils/message.go
- core/types/hash.go
- core/types/transaction.go
- node/consensus/block_executor.go
- node/types/block.go
- node/types/block_test.go
I came across what looks like some non-determinism in the computation of `accountsHash` while converting some uses of `sha256.Sum256` to our `types.Hash`/`types.Hasher`/`types.HashBytes`.
@charithabandi pls correct me if I'm wrong, but `ce.accounts.Updates()` code seems to range over a map, but even if it sorted internally I think it's right to have CE do a sort its way, as the other hashes do.
> accountsHash determinism, and global types.Hash use

- app/node/build.go
- cmd/kwil-cli/cmds/utils/message_test.go
- core/rpc/client/admin/jsonrpc/client.go
- core/rpc/json/admin/responses.go
- core/types/admin/types.go
- core/types/types.go
- node/config.go
- node/interfaces.go
- node/node.go
- node/node_live_test.go
- node/services/jsonrpc/adminsvc/service.go
- node/services/jsonrpc/usersvc/service.go
- node/store/store.go
Resolves https://github.com/kwilteam/kwil-db/issues/1119
Also makes basic impl of `(*Node).Status`, which further reveals some need for more methods from CE or another type for execution and app status rather than just consensus protocol.
> add TestSingleNodeMocknet and imp (*Node).Status

- node/pg/db.go
When a test or an application panics due to an orphaned transaction it will hang when trying to close the DB.  This change avoids the hang by automatically rolling back the orphaned transaction and closing the DB before the explicit panic.
For example:
```
2024-12-05 16:07:23.377 [INF] NODE1: Consensus message received {type=block_proposal sender=0281c655d760af1b41e47fa5614679d771eee25a6427ce797218517e210f475bab} 2024-12-05 16:07:23.377 [INF] NODE1: Already processing the block proposal {height=1}
engine_test.go:573: expected block hash 73f4a3e53c41fa8a06f05fafb0401228b991a5600f1a043ab9ee7c3c44ff409c, got 8d301bb8b1ce1e7d208ea06dd783ef8f5e6d314c4979b3d93ec5f55807a4714b
engine_test.go:573: expected block hash 73f4a3e53c41fa8a06f05fafb0401228b991a5600f1a043ab9ee7c3c44ff409c, got …
```
> pg: avoid hang on orphaned transcation panic

- README.md
I tried to fix the broken banner with https://github.com/kwilteam/kwil-db/pull/1127, but it only fixed the new path. The file also got renamed from `.jpeg` to `.jpg`, which I missed.
> fix banner name

- Taskfile.yml
- app/node/build.go
- node/consensus/engine_test.go
- node/node_live_test.go
- node/pg/db.go
Not just regular transactions.  This avoids annoying orphaned prepared transactions in the case where a bug results in closing the DB when there is an active transaction.
> clean up prepared transactions in (*DB).Close

- contrib/scripts/build/.go_variables
- node/pg/repl.go
- node/pg/repl_changeset.go
With prepared transactions, where we are hashing for commit ID and collecting changesets during migration period, the sequence of queries and resulting logical replication messages is like this:
```go
// - BEGIN;
// - mods: UPDATE / INSERT / DELETE
// - PREPARE TRANSACTION 'uid';
//	* msgs: Begin Prepared -> [update messages] -> Prepare (ready to commit)
// - COMMIT PREPARED 'uid';
//  * msgs: Commit Prepared (NO regular "Commit" message)
```
If we `ROLLBACK PREPARED` (after `precommit`), we are discarding the prepared transaction that `postgres` has written to disk.  This is what emits the `RollbackPreparedMessageV3` in the logical replication stream.
But since this is after we have done `PREPARE TRANSACTION`, we have already hashed the changes and collected the changeset and, …
> pg: in repl there is no fail, we get the stream or not

- cmd/kwil-cli/cmds/configure/configure.go
- cmd/kwil-cli/cmds/root.go
- cmd/kwil-cli/cmds/utils/ping.go
- cmd/kwil-cli/config/config.go
- cmd/kwil-cli/main.go
Neglected to push this yesterday.
For `kwil-cli`, this reorders the priority of config:
1. env
2. flags
3. config file (config.json)
This PR also makes it an error condition if the config file was specified (`--config/-c`) but it does not exists.  It is only not an error if it was not specified.
> cli: reorder config priority

- node/node.go
- node/peers/peers.go
This adds a basic connection manager that attempts to keep a target connection count. This is useful when a node, such as a validator, has the leader's address in bootnodes, but the leader is down.  When the leader is back, it is on the validator to be attempting reconnection with it's known but disconnected peers.
Resolves https://github.com/kwilteam/kwil-db/issues/1135
```
2024-12-09 15:17:54.087 [INF] PEERS: Active connections: 0, below target: 20. Initiating new connections.
2024-12-09 15:17:54.088 [WRN] PEERS: Failed to connect to peer 16Uiu2HAkx2kfP117VnYnaQGprgXBoMpjfxGXCpizju3cX7ZUzRhv: failed to dial: failed to dial 16Uiu2HAkx2kfP117VnYnaQGprgXBoMpjfxGXCpizju3cX7ZUzRhv: all dials failed
* [/ip4/127.0.0.1/tcp/6600] dial backoff
2024-12-09 15:17:55.088 [INF] PEERS: Active …
```
> node/peers: basic conn count mgr

- core/crypto/auth/signer.go
- core/types/block.go
- core/types/transaction.go
- core/utils/rw.go
- core/utils/writer.go
- node/block_processor/processor.go
- node/consensus/block.go
- node/consensus/interfaces.go
- node/consensus/leader.go
- node/interfaces.go
- node/mempool/mempool.go
- node/mempool/mempool_test.go
- node/node.go
- node/node_test.go
- node/nogossip.go
- node/store/memstore/memstore.go
- node/store/memstore/memstore_test.go
- node/store/store.go
- node/store/store_test.go
- node/tx.go
- node/types/interfaces.go
Both the block store and mempool types were still using opaque transctions (`[]byte`) from the early version of the p2p demo.  This updates both to use `*types.Transaction`.
This change stops short of updating the `Block` type to have a `Txns []*Transaction`  field instead of `Txns [][]byte`, but that change should also be made.  This can wait until the block data / chain RPCs are complete.  It will also require updating the block serialization code, although the effective binary serialization will be identical.
This also updates the mempool implementation and interface:
- internally there is a FIFO queue so that `PeekN` will return those at the front of the queue.  The maps still remain there for fast indexing and existence checks.
- add a `Remove` method that is the same as `Store(txid, …
> use structured transaction in store and mempool

- app/node/build.go
- config/config.go
- contrib/docker/compose/postgres/docker-compose.yml
- core/rpc/client/chain/interface.go
- core/rpc/client/chain/jsonrpc/client.go
- core/rpc/json/chain/commands.go
- core/rpc/json/chain/methods.go
- core/rpc/json/chain/responses.go
- core/types/chain/types.go
- node/block.go
- node/consensus/block.go
- node/consensus/interfaces.go
- node/interfaces.go
- node/node.go
- node/node_test.go
- node/services/jsonrpc/chainsvc/service.go
- node/services/jsonrpc/chainsvc/spec.go
- node/services/jsonrpc/funcsvc/service.go
This resolves #1121
All APIs listed in the issue are implemented under `chain` rpc namespace.
These APIs are not implemented:
- `/num_unconfirmed_txs`,  `chain.unconfirmed_txs` returned the total txs
- `/tx_search`, it's more useful for tx subscription, we don't have the needs yet
- `/block_search`, it's more useful for block subscription
- `/check_tx`
- `/commit`, I don't think we have this kind of info
> feat(rpc): chain RPCs

- app/node/node.go
- app/root.go
- config/config.go
This makes log outputs configurable again with `--log-output`.  The default is `stdout` and `kwild.log` (in root dir)
> configurable log outputs

- app/shared/display/message.go
- app/shared/display/message_test.go
- core/types/block.go
- core/types/block_test.go
- core/types/chain/types.go
- core/types/messages.go
- core/types/results.go
- core/types/transaction.go
- core/types/transaction_test.go
- node/block.go
- node/block_processor/processor.go
- node/block_processor/status.go
- node/block_processor/transactions.go
- node/block_processor/transactions_test.go
- node/consensus/block.go
- node/consensus/interfaces.go
- node/consensus/leader.go
- node/node.go
- node/node_test.go
- node/nogossip.go
- node/services/jsonrpc/adminsvc/service.go
- node/store/memstore/memstore.go
- node/store/memstore/memstore_test.go
- node/store/store.go
- node/store/store_test.go
```
types: use structured tx in block, no error Tx srlzn
This updates the block structure with a `Txns []*Transaction` field
insead of `[][]byte`.
This also updates transaction serialization so that it is guaranteed
not to error (except if a writer fails). This means that it supports
a nil Body even if that is invalid in a block. The Bytes() method may
be used instead of MarshalBinary for this.
Finally, two bytes for version are added to transaction and transaction
results serializations.
```
> structured tx in block

- cmd/kwil-cli/cmds/database/execute.go
Fixes a nil pointer dereference bug I introduced while making changes to `kwil-cli`
> kwil-cli: fixed nil pointer dereference

- node/engine/interpreter/context.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/planner.go
- node/engine/interpreter/values.go
- node/engine/parse/antlr.go
- node/engine/parse/ast.go
- node/engine/parse/gen/kuneiform_lexer.go
- node/engine/parse/gen/kuneiform_parser.go
- node/engine/parse/grammar/KuneiformParser.g4
- node/engine/pg_generate/generate.go
This PR fixes several bugs, including:
- slicing not working properly in the interpreter.
- nested action calls not working properly.
- loops over action calls not working properly
> engine: fix slices, nested actions, and loops over actions

- cmd/kwil-cli/cmds/database/batch.go
- cmd/kwil-cli/cmds/database/call.go
- cmd/kwil-cli/cmds/database/execute.go
- cmd/kwil-cli/cmds/database/flags.go
Fixes a small bug where not selecting a namespace does not default to the default namespace `main`.
> kwil-cli: minor improvements and bug fixes

- core/crypto/auth/auth_test.go
- core/crypto/auth/eth_personal_sign.go
- core/crypto/auth/eth_personal_sign_test.go
This makes the `(*EthSecp256k1Authenticator).Identifier` format the string in EIP-55 checksumed case.
> core/crypto/auth: checksummed eth address from Identifier

- node/node_live_test.go
- node/pg/db.go
- node/pg/test/testdb.go
Explicit rollback is if beginWriterTx() fails after creating the Consensus Tx, else the db.Close() will panic
> Rollback if the consensusTx creation is partially successful

- test/setup/admin_client.go
- test/setup/node.go
Adds the ability to contact the `kwil-admin` for each node.
> added admin client barebones

- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/schema.sql
This fixes a bug with foreign keys that @Yaiba found
> fix: engine incorrectly gives foreign keys to planner

- core/types/data_types.go
- core/types/data_types_test.go
- core/types/marshal_fuzz_test.go
- core/types/payloads.go
- extensions/precompiles/actions.go
- extensions/precompiles/values.go
- extensions/precompiles/values_test.go
- node/engine/functions.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/planner.go
- node/engine/interpreter/schema.sql
- node/engine/interpreter/sql.go
- node/engine/interpreter/sql_test.go
- node/engine/planner/logical/planner_test.go
This PR fixes several bugs within the engine. It fixes the bug that @KwilLuke hit where decimal arrays are not handled properly from the DB. It also adds better testing to the info namespace.
It slightly changes the info schema to make it easier to use. It also adds exponentiation to the engine.
> engine: better testing for `info` schema

- node/engine/planner/logical/planner.go
- node/engine/planner/logical/planner_test.go
This fixes a pointer de-reference bug that was caused when referencing an invalid column within an insert.
It also fixes a separate minor issue where a typecast for a subquery was not being handled correctly.
> planner: fix pointer dereference

- core/log/log.go
Sub loggers derived from the main `KWILD` logger were reset to Info level logging rather than maintaining the same level as the parent.  This fixes that.
> log: use parent logger level for sub loggers

- app/node/conf/conf.go
- app/node/conf/conf_test.go
- app/node/node.go
- app/node/start.go
- app/setup/genesis.go
- app/setup/init.go
- app/setup/testnet.go
- config/config.go
- node/txapp/txapp.go
- node/voting/voting.go
`init`, `testnet` and `autogen` will take `--db-owner` flag to configure the Owner, if not set, it sets it to the leader.
> set dbOwner as the leader when run with --autogen

- core/types/data_types.go
- core/types/decimal.go
- core/types/decimal_test.go
- core/types/encoded_value_test.go
- core/types/payloads.go
- core/types/results.go
- core/types/results_test.go
- core/types/uuid.go
- node/engine/functions.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/sql_test.go
- node/engine/interpreter/values.go
- node/engine/interpreter/values_test.go
- node/engine/parse/antlr.go
- node/engine/parse/ast.go
- node/engine/pg_generate/generate.go
- node/pg/db_live_test.go
- node/pg/stats.go
- node/pg/system.go
- node/pg/types.go
- node/services/jsonrpc/openrpc/reflect.go
- node/utils/conv/conv.go
- node/utils/conv/conv_test.go
Sorry, I should've split this up into separate PRs. It does 3 things:
1. It adds the ability to scan into values when using the Go client.
2. It moves the `decimal` package into `types`. It also renames some of the exported functions related to decimals to make it clear that they are for decimals (e.g. `NewExplicit` -> `NewDecimalExplicit`). Previously, it was clear that these were for decimals because they were in the decimals package, but now that is not the case.
3. It renames references to the Kuneiform's `decimal` type to `numeric`, to make it match Postgres more closely. This was actually a change I made in the new engine a while ago., there were just a few straggling things I hadn't updated. `decimal` still works as an alias to `numeric`.
> core: added scanning for results

- core/types/encoded_value_test.go
- core/types/payloads.go
In v0.10, we rename `blob` and `decimal` to be `bytea` and `numeric`. We still allow `blob` and `decimal`, they are simply aliased to `bytea` and `numeric`. We were not representing this aliasing in value decoding. This PR fixes that.
> added type aliases for encode

- common/context.go
- node/block_processor/interfaces.go
- node/block_processor/processor.go
- node/block_processor/transactions_test.go
- node/consensus/engine_test.go
- node/services/jsonrpc/usersvc/service.go
- node/txapp/txapp.go
This PR adds block hash to BlockContext, as requested by @Yaiba.
It makes a minor refactor to pass in the genesis config to txapp. I felt this was appropriate because
1. We were pretty much just destructuring `config.GenesisConfig` into 5-6 args.
2. txapp already relied on the `config` package
I'm happy to change it back though, no strong opinion.
> node: add block hash to BlockContext

- core/types/serialize/encode.go
- extensions/resolutions/credit/credit.go
- node/migrations/changesets.go
- node/migrations/migrations.go
- node/migrations/migrator.go
- node/rlp/rlp.go
This fixes RLP decoding.   Decoding with the `seriailize` package gets the codec from a prefix in the `[]byte`.  It is not specified manually.  That is only for encoding.
Example RLP support, e.g. from an extension:
```go
package main
import (
"bytes"
"github.com/kwilteam/kwil-db/core/types/serialize"
"github.com/kwilteam/kwil-db/node/rlp" // register RLP codec with serialize package
)
func main() {
s := "hi"
bts, err := serialize.EncodeWithEncodingType(s, rlp.EncodingTypeRLP)
if err != nil {
panic(err)
}
bts2, err := serialize.EncodeWithCodec(s, *rlp.Codec)
if err != nil {
panic(err)
}
if !bytes.Equal(bts, bts2) {
panic("not equal")
}
var s2 string
err = serialize.Decode(bts, &s2)
if err != nil {
panic(err)
}
println(s2) // "hi"
}
```
> fix rlp decode

- app/root.go
- app/shared/generate/generate.go
- app/shared/help.go
- app/shared/wrap.go
- cmd/kwil-cli/cmds/call-action.go
- cmd/kwil-cli/cmds/exec-sql.go
- cmd/kwil-cli/cmds/query.go
- cmd/kwil-cli/cmds/root.go
- cmd/kwil-cli/cmds/tableprint.go
- cmd/kwil-cli/cmds/utils/generate_key.go
- node/engine/functions.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/planner.go
- test/setup/jsonrpc_cli_driver.go
Small punchlist items in kwil-cli that I am fixing as I make the docs. Nothing major here, just formatting changes for outputs or minor bug fixes.
Changes so far include:
- fixing `kwil-cli utils generate-key`
- renaming flags for new CLI functions to make them more intuitive
- maintained ordering of columns when printing query results
- auto-formatting and wrapping for CLI `--help` flag based on terminal width
- fixed and added tests for a bug where special functions were not being copied properly to a new namespace
- Made `array_append` args optionally be compatible Postgres, but kept our modified version as well.
> Cli punchlist

- app/node/build.go
- app/node/deps.go
- app/node/namespace_manager.go
- app/node/node.go
- cmd/kwil-cli/cmds/database/call.go
- cmd/kwil-cli/cmds/database/flags.go
- cmd/kwil-cli/cmds/exec-action.go
- node/engine/interpreter/context.go
- node/engine/interpreter/interpreter.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/planner.go
- node/engine/interpreter/sql_test.go
- node/engine/types.go
- testing/testing.go
As discussed, I have added a way for other parts of Kwil to read the current set of namespaces.
Something worth noting is that namespaces can be read in the middle of a block, so it is not transactional within the engine (e.g. if a block has 10 txs, and a namespace is created in tx 1 of 10, the system will see it before the other 9 txs commit).
This can be fixed, but it requires writing to the manager at a higher level (in block processor)
> add namespace manager

- core/crypto/keys.go
- node/accounts/accounts.go
- node/accounts/accounts_test.go
- node/accounts/sql.go
This makes no functional or user visible changes, but it does alter how the account store tables work.
With
```json
"alloc": [
{
"id": "0xAfFDC06cF34aFD7D5801A13d48C92AD39609901D",
"key_type": "secp256k1",
"amount": 10000000000000000000000000000000000000000000
}
],
```
we had
```
┌─[ RECORD 1 ]──────────────────────────────────────────────────────────────────────────────┐
│ identifier │ \x14000000affdc06cf34afd7d5801a13d48c92ad39609901d09000000736563703235366b31 │
│ balance    │ 10000000000000000000000000000000000000000000                                 │
│ nonce      │ 0                                                                            │
└────────────┴──────────────────────────────────────────────────────────────────────────────┘
```
With this change we have
```
┌─[ RECORD 1 …
```
> accouts: composite primary key over id and id_type

- app/node/build.go
- app/node/namespace_manager.go
Removes panic on namespace manager
> node: remove namespace manager Ready() panic

- app/key/gen.go
- app/key/info.go
- app/node/start.go
- app/root.go
- app/seed/seed.go
- app/setup/genesis-hash.go
- app/setup/genesis.go
- app/setup/init.go
- app/setup/reset.go
- app/setup/testnet.go
- app/shared/bind/bind.go
- app/shared/display/format.go
- app/snapshot/create.go
Going through several small things that @KwilLuke mentioned yesterday
- some commands try to read `~/.kwild/config.toml` unnecessarily, leading to confusing errors if the file is invalid since it's really irrelevant to the command
- fix misuses of `display.PrintErr` and document proper use
- use the `conf.ActiveConfig`, which is the merged configuration in several commands instead of manually loading the toml file
- revise the `start` command's docs to reflect that it is no longer the default command
- `setup init` will error if the destination directory already exists.  Previous it ran with unpredictable results.
> improve several kwild cmd issues with config parsing and error handling

- app/node/conf/conf.go
- app/node/deps.go
- app/node/node.go
- config/config.go
- contrib/docker/compose/kwil/docker-compose.yml
- node/block_processor/processor.go
- node/consensus/block.go
- node/consensus/engine.go
- node/consensus/leader.go
- node/node.go
- node/nogossip.go
- node/pg/repl.go
- node/types/interfaces.go
This change primarily is cleanup and logging minimizations.  Part of this is avoiding endless spam of the warning `No connected peers and no known addresses to dial!` when running a single node network.  This lead to some `autogen` fixes.
> autogen, peercount, logging updates

- core/types/message.go
- core/types/message_test.go
- node/services/jsonrpc/usersvc/service.go
For testing and review.  Dont' merge unless tested with kwil-js
Convo with @KwilLuke:
https://kwilteam.slack.com/archives/C05RZNFKNJD/p1737575798988009
> remove duplicate auth/sig type from CallMessage

- common/common.go
Adds the ability for extensions to attach arbitrary info to a transaction context, which can be referenced later
> node: add SetValue and Value in tx context

- app/node/node.go
- app/setup/testnet.go
- config/config.go
- node/node.go
- node/p2p.go
WIP, just want CI running
```
$  ./kwild start -r .testnet/node0 --p2p.external-address 70.113.64.78:6666
...
2025-01-28 18:41:12.011 [INF] NODE: This node is 0226b3ff29216dac187cea393f8af685ad419ac9644e55dce83d145c8b1af213bd#secp256k1 @ [70.113.64.78:6600 127.0.0.1:6600 192.168.30.232:6600]
```
> p2p.external-address

- parse/analyze.go
Fixes ordering bug when using `distinct`
> fixed ordering bug for distinct

- app/node/node.go
- config/config.go
- core/types/params.go
- core/types/types.go
fixes the node start issue:
```
❯ ./.build/kwild start -r .net2
Error: genesis configuration failed sanity checks: migration status is invalid: ""
❯
```
> Genesis checks shouldn't involve migration status

- contrib/docker/kwild.dockerfile
- node/exts/erc20reward/ext.go
- node/exts/erc20reward/ext_test.go
- node/exts/erc20reward/meta/ext.go
- node/exts/erc20reward/meta/sql.go
- node/exts/erc20reward/reward/mtree.go
- node/exts/erc20reward/reward/mtree_test.go
- node/exts/erc20reward/sql.go
- test/_old/acceptance/docker-compose-dev.yml
- test/_old/acceptance/docker-compose.yml
- test/_old/integration/docker-compose-dev.yml
- test/_old/integration/docker-compose-migration.yml.template
- test/_old/integration/docker-compose.yml.template
- test/setup/node-compose.yml.template
This pr support a new extension method "list_wallet_rewards", which returns `["chain","chain_id","contract","etherscan","created_at","param_recipient","param_amount","param_block_hash", "param_root", "param_proofs"]`;  to support this I created a table `erc20rw_recipient_reward` when finalize a epoch.
Also rename :
- `erc20rw_pending_reward` table to `erc20rw_rewards`
- `erc20rw_epoch_reward` table to `erc20rw_epochs`
- `erc20rw_pending_signatures` table to `erc20rw_epoch_votes`
> ext(erc20rw): support list wallet rewards

- app/node/node.go
- node/node.go
- node/node_live_test.go
- node/opts.go
- node/p2p.go
- node/peers/backoff.go
- node/peers/backoff_test.go
- node/peers/peers.go
- node/statesync.go
This makes the startup peer connection (handled by `maintainMinPeers`) use exponential backoff on a per-peer basis, just like the reconnect logic started when a peer disconnects (initiated by the `network.Notifiee`)
This also fixes the regression with the `network.Notifiee` being de-registered from the Host.
Finally, this has the `P2PService` register dummy stream handlers for all of the "required" protocol IDs.  They are replaced with the actual handlers in `Node`  startup when the CE is ready to take over.
> Start connect backoff

- README.md
- contrib/docker/compose/kwil/docker-compose.yml
- contrib/docker/kwild.debug.dockerfile
- test/nodes/spamd/dockerfile
This fix the contrib/docker/compose/docker-compose to use subcmd
> fix(contrib): add missing subcmd to docker-compose

- app/key/info.go
- app/node/build.go
- app/node/node.go
- app/root.go
- app/rpc/gen-auth-key.go
- app/shared/display/format.go
- app/shared/help.go
- cmd/kwil-cli/cmds/root.go
- cmd/kwil-cli/main.go
- cmd/kwild/main.go
- node/node_live_test.go
- node/node_test.go
- node/p2p.go
- test/integration/kwild_test.go
- test/setup/compose.go
- test/setup/jsonrpc_cli_driver.go
- test/setup/node-compose.yml.template
- test/setup/node.go
This changes how the command line apps handle errors to ensure we have non-zero exit codes to the OS/shell while also maintaining our own output format.  This is important for scripting among other things.
The problem with cobra is that if we return an error from say `RunE`, [cobra will insist on prefixing the error message](https://github.com/spf13/cobra/issues/2226) with a text like `Error: ` which is no good for reasons.  We can sorta set this prefix, but it's a somewhat flawed implementation whereby we always end up with at least two spaces prefixing the output we want.  This is why we have had the `shared/display.PrintErr` always eating the error, I believe.
We get around this issue by continuing to swallow the error, but storing the error in the command's context, and then in …
> rework cmd app errors, permit non-zero exit code and custom output

- node/node_live_test.go
- node/node_test.go
- node/statesync_test.go
This makes `TestDualNodeMocket` use bootpeers like real apps rather than having the mocknet do it's `ConnectAllButSelf` magic.  Let's see if CI and my machine like this better.
More generally, we've started doing much more outside of the `Node` constructor and `Start`, so it might make sense to have these quick in-memory tests in some other node_test package that uses the server construction stuff in `app/node` directly so this is closer to reality.  This test came about before there was even an app using `Node`.
> node: use bootpeers in mocknet test instead of force connect

- cmd/kwil-cli/cmds/exec-action.go
- node/engine/interpreter/context.go
- node/engine/interpreter/interpreter.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/planner.go
- node/engine/interpreter/sql.go
- node/engine/interpreter/sql_test.go
- node/engine/interpreter/types.go
- node/engine/parse/antlr.go
- node/engine/parse/ast.go
- node/engine/parse/parse_test.go
- node/engine/pg_generate/generate.go
- node/engine/pg_generate/generate_test.go
- node/engine/types.go
Fixes several bugs:
- If a nil pointer de-reference was encountered in the engine, the engine did maintain transactionality
- `RETURN;` statements that don't return any values could sometimes cause DB deployment issues
- `RETURN SELECT` did not exit a function early, and effectively acted as a RETURN NEXT for all values in a query
- Resolves https://github.com/kwilteam/kwil-db/issues/1343, which was a minor CLI formatting issue
- Resolves https://github.com/kwilteam/kwil-db/issues/1344, which was a bug where functions that used pseudo-types failed.
> Fix engine

- cmd/kwil-cli/cmds/exec-action.go
https://github.com/kwilteam/kwil-db/pull/1350 Had a typo in an error message
> kwil-cli: fix error typo

- core/types/decimal.go
- core/types/uuid.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/values.go
- node/engine/interpreter/values_test.go
- node/pg/db_live_test.go
- node/pg/repl_changeset.go
- node/pg/types.go
- node/pg/types_test.go
Continuation of https://github.com/kwilteam/kwil-db/pull/1348, which resolved a crash in the collection of changesets from logical replication. 
```
The completes handling of NULL values in postgres arrays:
- The two functions that return []any (rather than scanning into
caller-provided variables of a certain type), Execute and
QueryRowFuncAny, now return []*T for any column that is an array.
Previously arrays would be returned as []T, which would not permit
identifying if the retrieved array cotained a NULL element.
pgx always returned an array as a []any, which permitted this, but
required type casting.  Handling of scalar columns is unchanged.
There was no crash if an array had a NULL, but when returned back
to go from e.g. Execute it would have the zero value for whatever
type was …
```
> pg: decoding and selecting nulls in arrays (part 2)

- app/node/namespace_manager.go
- app/setup/genesis.go
- app/setup/init.go
- app/snapshot/create.go
- node/engine/interpreter/planner.go
- node/exts/erc20reward/meta_extension.go
- node/exts/erc20reward/meta_schema.sql
- node/exts/erc20reward/meta_sql.go
- node/exts/ordered-sync/schema.sql
- node/exts/ordered-sync/sync.go
Fixes an issue where the new erc20 extensions are unable to start during migration. Also fixes an issue where paths for genesis state are not expanded in `kwild setup init`
> engine: fix extension startup during migration

- app/setup/testnet.go
Adding this flag to support scenarios where the nodes doesn't have incremental IPs. For example the nodes deployed on the cloud has random public IP addresses that needs to be set in the config.toml as External address and for boot peers. 
`./.build/kwild setup testnet -v 2 -n 2 -u -o .net --db-owner 0xc89D42189f0450C2b2c3c61f58Ec5d628176A1E7 -H "54.208.120.196,54.208.120.197,54.208.120.198,54.208.120.199"  `
Generated config file:
```
[p2p]
listen = '0.0.0.0:6600'
pex = true
bootnodes = ['0226b3ff29216dac187cea393f8af685ad419ac9644e55dce83d145c8b1af213bd#secp256k1@54.208.120.196:6600', '02c57268fc884fa88425c7e5c19d3af263d1c64dd8b8f3f8c0fb31bb622d1fdab8#secp256k1@54.208.120.197:6601', '021072159608e8bfa10102cc74d3e1b533dfdf1904538a61de42811cc3066de014#secp256k1@54.208.120.198:6602', …
```
> add hostname flag to setup testnet command

- app/node/start.go
- app/node/start_test.go
It seems like we forgot to re-add the ability to [configure extensions from the command line](<https://prerelease.kwil.com/docs/daemon/config/settings#configuration-source-priority>). This re-adds that
> kwild: re-add extension config flags

- core/types/decimal.go
- core/types/decimal_test.go
- node/exts/erc20reward/meta_extension.go
- node/exts/erc20reward/meta_schema.sql
- node/exts/erc20reward/meta_sql.go
- node/exts/erc20reward/meta_sql_test.go
- node/exts/erc20reward/named_extension.go
- node/exts/evm-sync/evm_state.go
- node/exts/evm-sync/evm_state_test.go
- node/exts/evm-sync/instance.go
- node/exts/evm-sync/instance_test.go
- node/exts/evm-sync/listener.go
- node/exts/ordered-sync/sync.go
- node/exts/ordered-sync/synchronizer.go
This PR standardizes rewards to always use uint256 values (rather than the scaled down values). It also optionally gives the ability to scale down / up based on a synced reward instances decimals.
This PR also reworks some of the evmsync logic to allow for us to sync many different logs from the same connection. It then uses this to add synchronization for epochs, so that we know when they are confirmed.
Finally, it fixes many bugs regarding syncing ethereum data. I've now tested syncing all necessary data and it all works as expected.
> erc20: extension info syncing pt 2

- node/engine/planner/logical/planner.go
- node/engine/planner/logical/planner_test.go
This PR fixes two bugs in the query planner that @Yaiba found.
The first bug occurred when we have an UPDATE that does not have a FROM nor WHERE, and references the updated table as part of the expression. It was unable to reference the updated table in this case.
The second bug was not technically a bug, but it was a really confusing error message. If a user had an ON CONFLICT clause targeting a composite index, and it referenced an unknown column, it would say that a unique index did not exist on those columns, rather than complaining that the column itself did not exist.
> planner: fix update and upsert bugs

- app/node/node.go
- node/consensus/block.go
- node/consensus/engine.go
- node/consensus/follower.go
- node/consensus/leader.go
- node/node.go
The ensures that fatal CE errors (those which kill the consensus event loop other than parent context cancellation) are returned to the the caller of Start. This fixes a halted / dead CE not stopping the node.
This also reduces a lot of duplicate error logging when the error is continually passed up the call stack.
> ce,node: CE crash must stop node

- node/engine/interpreter/values.go
This fixes a bug found by @Yaiba, where a nil array was not detected as nil, but instead detected as a 0-length array, if it was passed via an extension.
> fix null value bug in engine

- app/node/build.go
- app/shared/display/message_test.go
- config/config.go
- core/crypto/auth/signature_test.go
- core/crypto/auth/signer.go
- core/types/block.go
- core/types/block_test.go
- core/types/hash_test.go
- core/types/hex_test.go
- core/types/message.go
- core/types/params.go
- core/types/params_test.go
- core/types/time_test.go
- core/types/transaction.go
- core/types/transaction_test.go
- core/types/varint_test.go
- core/utils/rw.go
- node/block.go
- node/consensus/block.go
- node/protocol.go
- node/statesync.go
- node/store/opts.go
- node/store/store.go
- node/store/store_test.go
- node/txapp/mempool.go
- node/types/commit.go
- node/types/consensus.go
- node/voting/validators.go
The PR starts with enforcing the consensus parameter (in genesis.json) for max block size.
This also led to several changes in block and transaction serialization, primarily the use of variable length integers in length-prefixed data, which includes many fields in the transaction and transaction body.  None of the payloads that JS would have to serialize are changed.  The size of a block with many fairly small transactions is drastically reduced.
The `SerializeSize` methods are added or improved, as these are required for efficient size checks without actually allocating huge amounts of memory.
Finally, this addresses some minor issues related to the block store:
- much of the config was not working as intended, namely the logger was being overriden
- our default of no-compression (an …
> consensus,store: enforce block size limits, compact serializations, misc badger fixes

- node/exts/erc20reward/meta_extension.go
- node/exts/evm-sync/listener.go
Fixes an issue where the Ethereum RPC gives us logs out of order, which our resolution was not expecting.
> evm-sync: fix blocks syncing out of order

- node/engine/interpreter/context.go
- node/engine/planner/logical/errors.go
- node/engine/planner/logical/planner.go
- node/engine/planner/logical/planner_test.go
- node/engine/planner/optimizer/pushdown_test.go
Actions are not allowed to be used within SQL. If a user tries to, two things may happen:
1. If the action has the same name of the built-in function, it will just use the built-in function. This is actually sort've misleading from the perspective of the user, because referencing that same function in an action will call the action (and all built-in functions can be called this way as well).
2. If there is not a built-in function, it simply says "function does not exist", rather than informing the user that it is illegal to use actions in a query.
This PR changes this, so that the query planner will inform the user that it cannot reference these functions.
Resolves: https://github.com/kwilteam/kwil-db/issues/1355
> engine: better error messages for actions used in SQL

- common/common.go
- node/services/jsonrpc/usersvc/service.go
- test/acceptance/act_test.go
JSON stringifies int64 so that we can handle high precision int values in JavaScript.
> rpc: json stringify numbers

- app/node/prof.go
- config/config.go
- core/log/log.go
- node/services/jsonrpc/server.go
This was a hotspot in performance tests.  This is not feature that needs to be enabled by default.  It can be a convenience to reduce response sizes if there are large compressible responses AND the operator doesn't want to deploy a proper reverse proxy to offload this task.  Hence, this disables it by default and provides the option to enable it for quick bandwidth reduction at the expense of increased CPU.
> rpc,config: disable RPC response compression by default, add setting

- app/shared/bind/bind.go
Add the ability to bind flags for `map[string]string`
> kwild: add map[string]string flag binding

- node/engine/interpreter/context.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/planner.go
- node/engine/planner/logical/planner.go
- node/engine/planner/logical/planner_test.go
This PR adds caching for statements in the interpreter, removing the need to redundantly parse, analyze, and generate SQL for statements that don't change. The cache is invalidated any time any table is changed; this is because a change in the DB schema may change what is necessary to make a query deterministic.
This PR also fixes a bug that I coincidentally found while clicking through the query planner looking for something else. It was not properly applying default ordering to window functions.
> engine: cache prepared statements

- .github/workflows/ci-main.yaml
- .github/workflows/ci-release.yaml
- README.md
- Taskfile.yml
- contrib/docker/compose/kwil/docker-compose.yml
- contrib/docker/compose/postgres/docker-compose.yml
- contrib/docker/postgres.dockerfile
- test/setup/node-compose.yml.template
- testing/testing.go
This is the pg part of https://github.com/kwilteam/kwil-db/pull/1413 that went into `release-v0.9`.
This updates the base postgres image to 16.8, and increases `max_locks_per_transaction` to 4096 (from 256).
> update postgres docker: more tx locks, v 16.8

- node/consensus.go
- node/consensus/follower.go
- node/dht.go
- node/node.go
- node/nogossip.go
- node/p2p.go
- node/peers/gate.go
- node/peers/peers.go
- node/statesync_test.go
This fixes several things:
- the block proposal announcement stream handler `blkPropStreamHandler` could be abused to download block proposals multiple times because the sequence of `AcceptProposal` => download => `NotifyBlockProposal` was not made atomic.  This is fixed with a mutex.
- `AcceptProposal` does leader signature verification *first* before any other action such as retrieving the block from the block store.  This allows the proposal handler to return quite quickly if the annoucement was illegitimate (spam)
- followers, such as normal validators, now immediately reannounce a block proposal to their peers on first receipt of a new valid proposal.  This allows sparse network connectivity, including validators that are not directly connected to the leader.
- It was discovered that …
> node,peers: proposal annoucement and PEX fixes

- core/types/block.go
- core/types/transaction.go
- node/block_processor/processor.go
- node/block_processor/status.go
- node/block_processor/transactions.go
- node/block_processor/transactions_test.go
- node/consensus/block.go
- node/consensus/interfaces.go
- node/consensus/leader.go
- node/interfaces.go
- node/mempool/mempool.go
- node/mempool/mempool_test.go
- node/node.go
- node/node_test.go
- node/nogossip.go
- node/services/jsonrpc/chainsvc/service.go
- node/store/store.go
- node/tx.go
- node/types/interfaces.go
- node/types/transaction.go
This updates `core/types.Transaction` a.k.a. `ktypes.Transation` with an unexported `cachedHash` field, which is only populated or referenced via the new `HashCache` method, rather than modifying the `Hash` method to do this automatically.  A few reasons are outlined in the docs, but they include concurrency concerns, needless allocs in many cases, the tx mutability gotchas particularly in client side applications.
This also removes the `node/types.NamedTx` which was used in a handful of places to pair the hash with the `core/types.Transaction`, replacing `NamedTx` with `node/types.Tx` for brevity.  This new types adds a constructor `NewTx` that computes the has on construction.  The `Hash()` method of this type shadows the embedded `types.Transaction`'s method to return this stored hash. …
> core/types,node/types: add cached tx hash to ktypes.Transaction, create node/types.Tx

- node/block.go
- node/consensus.go
- node/consensus/engine.go
- node/consensus/engine_test.go
- node/consensus/follower.go
- node/consensus/messages.go
- node/interfaces.go
- node/node.go
- node/node_test.go
This addresses a strange proposal announcement amplification that can occur given the right timing, which @charithabandi  observed once but could not easily reproduce.
In short, to support reannoucement of block proposals as well as preventing malicious spam proposals from stacking up behind the consensus event loop, we made the entire proposal stream handler atomic w.r.t. `AcceptProposal` => download = `NotifyBlockProposal`.  **However**, `NotifyBlockProposal` is mostly asynchronous, meaning the next call to `AcceptProposal` will return true and allow the same proposal, which includes a full block, to be downloaded again and queued in another consensus msg for `NotifyBlockProposal`.
To resolve this, we take a nearly identical approach to that used with `AcceptCommit` and its stream …
> node,consensus: no duplicate proposals allowed

- node/consensus/block.go
- node/consensus/engine.go
- node/consensus/leader.go
- node/consensus/lock.go
- node/consensus/lock_test.go
- test/stress/harness.go
This adds `node/consensus.PriorityLock` that is like a normal mutex but:
- `Lock` guarantees FIFO when acquired, no issues with sleeping goroutines in the `sync.Mutex` breaking ordering
- `PriorityLock` jumps the line, getting the lock ahead of others that used `Lock`
This is intended in the very specific use case of CE where the `mempoolMtx` was locked in:
- `commit`: block commit, priority
- `prepareBlockProposal`: leader preparing block proposal, priority
- `QueueTx`: ingest new tx from either p2p announce or RPC broadcast, NOT priority
All of the "priority" cases are sequential, never concurrent with each other.  Only the `QueueTx` spot can be concurrent and at any time, as it is triggered from external sources.
This eliminate the one bad spot of mutex contention revealed by running …
> node/consensus: priority lock for CE business to preempt tx influx

- node/consensus/block.go
- node/consensus/engine.go
- node/consensus/engine_test.go
- node/node.go
- node/nogossip.go
This PR ensures the FIFO consistency to the outgoing transaction announcements to maintain the nonce ordering.  So all the transaction announcements are routed through a TxQueue to enforce this order.
> order transactions announcements in the order they are received

- app/setup/genesis.go
- app/setup/testnet.go
- config/config.go
With this PR
- The `kwild setup testnet` command will now generate non-deterministic private keys for the nodes.
- The runtime sanity checks for the genesis config, now checks if the `pubkey` and the `key_type` of the genesis validators are valid.
- `setup` commands now does validation checks on the validator flags
> testnet setup command to generate non-deterministic private keys

- core/client/client.go
- core/rpc/client/user/jsonrpc/methods.go
- core/rpc/client/user/txsvc.go
- core/rpc/json/user/commands.go
- core/rpc/json/user/methods.go
- core/types/message.go
- node/engine/interpreter/interpreter.go
- node/engine/interpreter/roles.go
- node/engine/interpreter/roles_test.go
- node/engine/interpreter/schema.sql
- node/engine/interpreter/sql.go
- node/engine/interpreter/sql_test.go
- node/services/jsonrpc/usersvc/service.go
Adds an RPC endpoint for authenticated queries. It also automatically uses the endpoint if the client has a private key.
This PR also fixes a bug I found in our roles system, where certain types of fine grained permissions could be lost if a node restarts.
> rpc: add authenticated query

- node/exts/erc20-bridge/signersvc/signer.go
- node/peers/peers.go
- node/pg/repl.go
The spam of peer logs complaining about "no addresses" for a peer is a result of the node having an **incoming** connection with a peer that is both not routable (behind NAT with no port forwarding, or just a firewall, etc.) and has not configured `external_address`.  This silences those logs, which as it turns out are normal.
This also silences the "Commit hash" log from the `node/pg` logical replication stream.  It will be logged in CE when needed.
Finally, this converts a `time.Sleep` in the erc20_bridge into a select with a with `ctx.Done()` so that it does not hang for a big on shutdown.
> more log fixes

- node/exts/erc20-bridge/erc20/meta_extension.go
- node/exts/erc20-bridge/erc20/meta_sql.go
- node/exts/erc20-bridge/signersvc/signer.go
- node/exts/evm-sync/instance.go
- node/exts/ordered-sync/sync.go
This pr fix issue that when `unuse` an erc20 bridge ext, the listener topic is still registered.
Also add the support to update `period` config when re-use the existing erc20 bridge
> Fix/bridge: properly unuse a erc20 bridge

- contrib/docker/postgres.dockerfile
- node/block.go
- node/consensus.go
- node/consensus/blocksync.go
- node/consensus/engine.go
- node/nogossip.go
Even a brief transient network failure will make a syncing node shutdown.  A node should never shutdown in this case.
This also updates some of the progress logs so that they are always on to/from boundaries modulus 100 rather than whatever it was at at startup.
I need to chat with @charithabandi about retries
> node,consensus: robust to transient network failure

- node/engine/interpreter/interpreter.go
- node/engine/interpreter/interpreter_test.go
- node/engine/pg_generate/generate.go
- node/engine/pg_generate/generate_test.go
Fixes an error where the network can halt with a `conn busy` error. This is a short-term fix; it prevents users from making scalar function calls while looping over a SQL statement. We can fix this by having go implementations of the scalar functions, but getting go implementations that match Postgres's is very non-trivial, and will likely introduce bugs.
> engine: fix conn busy error

- core/client/client.go
- test/stress/hammer.go
- test/stress/harness.go
- test/stress/main.go
- test/stress/scheme.go
`-cl N` runs with `N` simultaneous instances with different keys.
The first one is special if `-key` is used.  The first one is responsible for deploying the namespace, or ensuring it is already deployed.  Only then do the rest follow.
For instance, to start 40 concurrent clients with unique keys, each doing 10 action executions ("posts") per block, with a post content length of up to 1461 bytes (variable length with (`-vl`), on a namespaces (`stress_xqbsioz1`) which should already exists since no key is given for the first client: 
```
./stress -ec 10 -el 1462 -ns stress_xqbsioz1 -vl -host http://44.x.y.z:8484 -cb -ei 1ms -ne -cl 40
```
> test: multi-key stress tool

- testing/testing.go
Resolves an issue raised by the idOS team here: https://kwilteam.slack.com/archives/C0578NPEU21/p1741700425614239
> testing: detect new execution error field in testing framework

- app/node/build.go
- node/block_processor/interfaces.go
- node/block_processor/processor.go
- node/block_processor/transactions.go
- node/block_processor/transactions_test.go
- node/consensus/block.go
- node/consensus/blocksync.go
- node/consensus/engine.go
- node/consensus/engine_test.go
- node/consensus/follower.go
- node/consensus/interfaces.go
- node/consensus/leader.go
- node/node_live_test.go
- node/services/jsonrpc/usersvc/service.go
- node/txapp/mempool.go
- node/types/sql/sql.go
This PR fixes, the DB read access contention that's holding back the consensus engine from making progress. CE will now use reservedReads for DB access within the consensus path. 
Also fixes the `Closed the DB with an active transaction` issue in the failure scenarios during catchup.
> Fix the contention on the DB read accesses

- core/rpc/json/user/responses.go
- node/accounts/accounts.go
- node/block_processor/interfaces.go
- node/block_processor/processor.go
- node/block_processor/transactions_test.go
- node/consensus/engine_test.go
- node/nogossip.go
- node/services/jsonrpc/usersvc/service.go
- node/services/jsonrpc/usersvc/user.openrpc.json
- node/txapp/txapp.go
This addresses a poor last minute design change to the RPC's `AccountResponse` which added a height field.  It turns out that this completely defeated the important account info caching at different levels, actually guaranteeing the use of a DB read-only transaction to service a `user.account` RPC.  This reverts that change.
This also modifies how the `NumAccount` method works so that it gets height along with count in the same DB transaction rather than making that the caller's (`Service`) job.
> fix poor use of DB getting height for account and numAccounts RPCS

- testing/testing.go
- testing/testing_test.go
Fixes an issue where errors returned from an extension are not handled properly in the testing package. Also adds some basic tests to the testing package to confirm this.
> testing: fix error return bug

- cmd/kwil-cli/cmds/call-action.go
- cmd/kwil-cli/cmds/database/call.go
- cmd/kwil-cli/cmds/database/query.go
- cmd/kwil-cli/cmds/exec-action.go
- cmd/kwil-cli/cmds/query.go
- core/client/client.go
- core/client/example/main.go
- core/client/types/client.go
- test/acceptance/act_test.go
- test/setup/jsonrpc_cli_driver.go
- test/specifications/dsl.go
- test/specifications/namespace.go
- test/stress/hammer.go
- test/stress/transport.go
Authenticated query became the default recently if the client has a Signer (private key) configured.
This provides a way to use legacy unauthenticated queries even when your client has a private key configured.
The use case is that very often a simple query into the `'info'` name space requires no authentication out of the box, but doing auth incurs an extra RPC round trip to get a challenge (and associated server overhead with creating, persisting, and verifying the challenge and signature).  In the specific case of stress testing, with enough keys it will fail to get a challenge.
> client,kwil-cli: skip auth option for query

- core/types/decimal.go
- node/exts/erc20-bridge/erc20/meta_extension.go
- node/exts/erc20-bridge/erc20/meta_sql.go
- node/exts/erc20-bridge/signersvc/eth.go
- node/exts/erc20-bridge/signersvc/multicall.go
- node/exts/erc20-bridge/signersvc/signer.go
- node/exts/evm-sync/chains/chains.go
- node/exts/evm-sync/listener.go
- node/exts/ordered-sync/synchronizer.go
This fix the issue where a vote is casted again, the signer should skip vote, but server should handle this
This pr fixes multiple issues:
- [890f74b](https://github.com/kwilteam/kwil-db/pull/1465/commits/890f74b706a218f8dd630e984099508186cee3c6) fix epoch conflict when a vote is re-casted
- [a10fac5](https://github.com/kwilteam/kwil-db/pull/1465/commits/a10fac518895eb124d51b818d8f85bb2447b5a80) a naive but effitive way to avoid eth RPC provider throttle.
-  [0f3c3a3](https://github.com/kwilteam/kwil-db/pull/1465/commits/0f3c3a35ff0a46a543a8474f9694932c155e7e6d) fix decimal operation lose precision issue, due to a mis use of function
- [bb06f91](https://github.com/kwilteam/kwil-db/pull/1465/commits/bb06f91963050c5eaaef64fb4741fbddc35de8f8) add check user balance before 'lock'
- …
> fix(bridge): multiple issues

- node/engine/interpreter/context.go
- node/engine/interpreter/interpreter_test.go
Fixes a bug where in-line SELECT statements would improperly have access control rules added.
If an in-line SELECT (a SELECT that is not a standalone statement, but instead part of a for loop or return) is used and SELECT is revoked, then the engine would improperly complain that the user did not have the correct privilege. This was not caught previously because the only time this is possible is if SELECT is used in FOR or RETURN, and any test we have that checks for revoking SELECT privileges did not also try to execute an action that uses either FOR or RETURN SELECT with a private key that does not have permission to execute ad-hoc SELECTs.
The issue is fixed by simply adding an additional piece of logic that informs out interpreter if we are in an action, and if so, disabling privilege …
> engine: fix bug where in-line selects can be revoked

- node/engine/interpreter/built_in_func_test.go
- node/engine/interpreter/interpreter.go
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/values.go
Adds native go implementations for array functions, as requested by @outerlook.
> engine: add native array func implementations

- core/types/payloads.go
- core/types/payloads_fuzz_test.go
Adds fuzz testing for the `EncodeValue` function. It also fixes 3 bugs in `EncodeValue`, and removes some redundant code and makes minor improvements:
- nil byte slices were not being encoded properly. They were being encoded with data in the `Data` field, which is incorrect.
- typed nil values were not being encoded properly, (e.g. `var nilVal []string = nil`).
- nil pointers were not being encoded
- Makes an error message for empty arrays more clear. Previously, it read that all array values were empty, however it actually checked if there were no values at all
- Removes a redundant case statement that is impossible
> core: add EncodeValue fuzz testing

- node/engine/interpreter/interpreter_test.go
- node/engine/planner/logical/planner.go
- node/engine/planner/logical/planner_test.go
This PR fixes a bug found by @outerlook where default ordering applied to window functions actually changed the functional output of a window function. Ordering on window functions actually changes the window itself, thus leading to a semantically different execution result.
This PR removes the orderings applied to aggregates used in functions altogether, as further investigation has shown that they actually aren't necessary. I've included in the code a link to a resource that explains how window functions break ties, and why default ordering is thus not a problem.
> engine: fix window function ranking bug

- node/consensus.go
- node/consensus/engine.go
- node/consensus/engine_test.go
- node/consensus/leader.go
- node/consensus/messages.go
- node/consensus_test.go
- node/interfaces.go
- node/node.go
- node/node_test.go
This PR fixes a data race issue in the consensus engine that occurs when accessing the `ce.leader` field. The issue arises when block proposal handling and role updates happen concurrently. Specifically, `ce.leader` is incorrectly accessed in `NotifyBlockProposal` to set the block proposal's sender as the current leader. This is problematic not only because the field is accessed without proper locking but also because it assumes that the proposal always comes from the current leader, which is not guaranteed (maybe a leader change scenario)
The fix involves including the sender information directly in the block proposal message, and accessing `ce.leader` fields in the stream handlers and their CE counterparts.
> data race accessing ce.leader

- core/types/block_fuzz_test.go
- node/block_processor/processor.go
- node/statesyncer.go
Currently, nodes joining the network via state sync are experiencing failures when downloading large snapshots (~2GB). This occurs because:
1. The current implementation launches concurrent fetchers for all the chunks, each requesting chunks of up to 16MB
2. Each chunk request has a hard 1-minute timeout which is more than reasonable for 
3. All chunk requests compete for network bandwidth, thereby leading to the request timeouts. (very evident with large chunk sizes)
The PR fixes this by reducing the number of concurrent chunk requests issued by the joining node to reduce the network load and giving enough bandwidth for these requests to succeed.
> limit the concurrent chunk requests issued during statesync

- node/node.go
- node/node_live_test.go
- node/node_test.go
- node/statesync_test.go
`peerIDForValidator` by default assumes the keyType of the validators to be `secp256k1`, this PR fixes that to accept `ed25519` keys. Also adds consensus tests for both keys
> support ed25519 keys in the node and consensus engine

- go.mod
- go.sum
- node/engine/interpreter/interpreter_test.go
- node/engine/interpreter/values_test.go
- node/engine/parse/antlr.go
- node/engine/parse/parse_test.go
- node/engine/pg_generate/generate_test.go
This PR adds better test coverage for the parser and engine. It also finds a very minor bug in the parser, where it would incorrectly parse out default ordering. This issue isn't seen when using Kwil holistically because it is hidden by the default ordering, but if you use the `parse` package as a standalone package you would hit it.
> add better test coverage for parser

- core/rpc/json/chain/commands.go
- core/rpc/json/chain/methods.go
- core/rpc/json/chain/responses.go
- core/types/chain/types.go
- go.mod
- go.sum
- node/block.go
- node/services/jsonrpc/chainsvc/chain.openrpc.json
- node/services/jsonrpc/chainsvc/service.go
- node/services/jsonrpc/chainsvc/spec.go
- node/store/memstore/memstore.go
- node/store/memstore/memstore_test.go
- node/store/store.go
- node/store/store_test.go
- node/types/interfaces.go
This commit adds a new RPC method chain.block_header, which involved implementaion of new GetBlockHeaderByHeight and GetBlockHeader methods on *Node, *MemBS and *BlockStore.
Also, the stale rpc spec version was updated.
Resolves #1506
Feature request.
After configuring PostgreSQL, I started a test kwild daemon using `kwild start --autogen` and manually tested the new rpc method
```txt
~ kwil-db % curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"chain.block_header","params":{"height":100},"id":1}' http://0.0.0.0:8484/rpc/v1 | jq
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"Version": 0,
"Height": 100,
"NumTxns": 0,
"PrevHash": "caefd257cbf82d59339d69e046ba45bdfd89edf12c23bf2c38e22c392f8df7e5",
"PrevAppHash": …
```
> multi: Add new RPC method `chain.block_header`

- node/statesync.go
- node/statesync_fallback_test.go
- node/statesync_test.go
- node/statesyncer.go
Implements “Option C – graceful reject” for state-sync verification:
1. `VerifySnapshot` now detects the `0x00` sentinel sent by a provider that **does have connectivity but no snapshot** and classifies the snapshot as `VerificationInvalid`.  
2. When all trusted providers are unreachable we now back-off for 5 s before retrying to avoid tight log loops.  
3. Adds a small, focused test-suite that covers:  
• fallback to latest verifiable snapshot (`TestStateSyncFallback`)  
• catalogue deduplication across multiple peers (`TestSnapshotCatalogDedup`)  
These changes stop the node from downloading chunks for snapshots that trusted providers cannot vouch for and drastically reduce log-spam / wasted bandwidth.
- Closes https://github.com/trufnetwork/kwil-db/issues/1524
Previously the node …
> fix: graceful-reject snapshots unverifiable by trusted providers

- node/block.go
- node/blocksync_sampling_test.go
- node/consensus.go
- node/node.go
- Added a peer-height cache (`peerBest`) that records each peer’s best known height and last-seen time.  
- `getBlkHeight` now:
– filters out peers that are certainly behind,  
– samples a larger fraction of peers in small networks (all peers ≤ 5; ≥3 or ⅓ ≤ 15; ≥3 or ⅕ otherwise).  
- Introduced periodic GC (`gcPeerCache`) to cap map size and age-out stale entries.  
- Reduced log noise:
– consensus ignores proposals > 100 blocks ahead.  
- Inline comments explain “why” for future maintainers.
Closes #1527 — block sync could stall when the single sampled peer was behind.
Previously we queried only ⌈N·0.2⌉ peers (min 1). If that peer lagged, the node stopped advancing.  
The new cache + adaptive sampling keeps sync progressing while minimising unnecessary network traffic.
1. Added unit …
> chore: Smarter peer-sampling for block sync

- node/pg/conn.go
- node/pg/db_live_test.go
- node/pg/query.go
- node/pg/types.go
Exporting `DecodeFromPG` and `OidTypesMap` is very helpful for fixing tx problems in https://github.com/trufnetwork/node/pull/1036. Otherwise it would be a burden to maintain synchronization between our typings.
This PR doesn't touch anything other than exporting those functions
> chore: export type map utility
